In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2

from tqdm import tqdm
from glob import glob
import os
import json 
import timm
import torch
from torch import nn
from torchvision import models
from torch.utils.data import Dataset, DataLoader
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split, StratifiedKFold
import albumentations as A

# PlatVillage

In [2]:
village_data = os.listdir('./data/public/PlantVillage')
label_encoder = {}
for idx, data_name in enumerate(village_data) :
    label_encoder[idx] = data_name

label_decoder = {val:key for key, val in label_encoder.items()}
display(label_decoder)
display(label_encoder)

{'Apple___Apple_scab': 0,
 'Apple___Black_rot': 1,
 'Apple___Cedar_apple_rust': 2,
 'Apple___healthy': 3,
 'Blueberry___healthy': 4,
 'Cherry_(including_sour)___healthy': 5,
 'Cherry_(including_sour)___Powdery_mildew': 6,
 'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot': 7,
 'Corn_(maize)___Common_rust_': 8,
 'Corn_(maize)___healthy': 9,
 'Corn_(maize)___Northern_Leaf_Blight': 10,
 'Grape___Black_rot': 11,
 'Grape___Esca_(Black_Measles)': 12,
 'Grape___healthy': 13,
 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)': 14,
 'Orange___Haunglongbing_(Citrus_greening)': 15,
 'Peach___Bacterial_spot': 16,
 'Peach___healthy': 17,
 'Pepper,_bell___Bacterial_spot': 18,
 'Pepper,_bell___healthy': 19,
 'Potato___Early_blight': 20,
 'Potato___healthy': 21,
 'Potato___Late_blight': 22,
 'Raspberry___healthy': 23,
 'Soybean___healthy': 24,
 'Squash___Powdery_mildew': 25,
 'Strawberry___healthy': 26,
 'Strawberry___Leaf_scorch': 27,
 'Tomato___Bacterial_spot': 28,
 'Tomato___Early_blight': 29,
 'Toma

{0: 'Apple___Apple_scab',
 1: 'Apple___Black_rot',
 2: 'Apple___Cedar_apple_rust',
 3: 'Apple___healthy',
 4: 'Blueberry___healthy',
 5: 'Cherry_(including_sour)___healthy',
 6: 'Cherry_(including_sour)___Powdery_mildew',
 7: 'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot',
 8: 'Corn_(maize)___Common_rust_',
 9: 'Corn_(maize)___healthy',
 10: 'Corn_(maize)___Northern_Leaf_Blight',
 11: 'Grape___Black_rot',
 12: 'Grape___Esca_(Black_Measles)',
 13: 'Grape___healthy',
 14: 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)',
 15: 'Orange___Haunglongbing_(Citrus_greening)',
 16: 'Peach___Bacterial_spot',
 17: 'Peach___healthy',
 18: 'Pepper,_bell___Bacterial_spot',
 19: 'Pepper,_bell___healthy',
 20: 'Potato___Early_blight',
 21: 'Potato___healthy',
 22: 'Potato___Late_blight',
 23: 'Raspberry___healthy',
 24: 'Soybean___healthy',
 25: 'Squash___Powdery_mildew',
 26: 'Strawberry___healthy',
 27: 'Strawberry___Leaf_scorch',
 28: 'Tomato___Bacterial_spot',
 29: 'Tomato___Early_blight',
 30: '

# custom dataset 정의

In [3]:
class VillageDataset(Dataset) :
    def __init__(self, files, transform, mode='train') :
        super(VillageDataset, self).__init__()
        self.files = files
        self.transform = transform
        self.mode = mode
        
    def __len__(self) :
        return len(self.files)
    
    def __getitem__(self, idx) :
        file_path = self.files[idx]
        
        label = label_decoder[file_path.split('\\')[-2]]
        
        img = cv2.imread(file_path)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        img = self.transform(image=img)['image']
        img = img.transpose(2, 0, 1)
        
        return torch.tensor(img, dtype=torch.float32) / 255.0, torch.tensor(label, dtype=torch.long)

# Dataloader w/o kfold

In [4]:
train_transforms = A.Compose([
                A.Resize(224 ,224),
                A.OneOf([
                    A.Rotate(),
                    A.HorizontalFlip(),
                    A.VerticalFlip()
                ], p=1)
            ])

val_transforms = A.Compose([
    A.Resize(224,224)
])

train = glob('./data/public/PlantVillage/*/*.JPG')
print("total : ", len(train))
label_list = [label_decoder[img_path.split('\\')[-2]] for img_path in train]

train, val = train_test_split(train, test_size=0.2, shuffle=True, stratify=label_list)
print("train : ", len(train))
print("val : ", len(val))
display(train)
train_dataset = VillageDataset(train, train_transforms)
val_dataset = VillageDataset(val, val_transforms)

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=16, shuffle=False)

total :  54304
train :  43443
val :  10861


['./data/public/PlantVillage\\Blueberry___healthy\\9039b699-aa44-4671-b63e-b9eba802976a___RS_HL 2505.JPG',
 './data/public/PlantVillage\\Soybean___healthy\\69fd19b2-93b5-4150-8ba9-0d624a6b00e4___RS_HL 3676.JPG',
 './data/public/PlantVillage\\Potato___Late_blight\\9570095c-02e9-497b-bec1-4e526f3462e5___RS_LB 2815.JPG',
 './data/public/PlantVillage\\Peach___Bacterial_spot\\767e3ee3-996b-48f9-b587-0b19e0eb3569___Rut._Bact.S 1451.JPG',
 './data/public/PlantVillage\\Tomato___Spider_mites Two-spotted_spider_mite\\0956a6ef-18ce-4a82-a9a1-ca41d07ae13f___Com.G_SpM_FL 9371.JPG',
 './data/public/PlantVillage\\Soybean___healthy\\2617acc7-e60c-4bed-abcc-64fdddf0d94c___RS_HL 6454.JPG',
 './data/public/PlantVillage\\Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot\\b53702bb-dfd5-4791-a550-d691cdb8a822___RS_GLSp 4379.JPG',
 './data/public/PlantVillage\\Cherry_(including_sour)___healthy\\472fd482-aec7-4e73-86d1-7161f6a5024b___JR_HL 4178.JPG',
 './data/public/PlantVillage\\Cherry_(including_sour)___Po

# DataLoader w/ kfold

In [5]:
img_list = glob('./data/public/PlantVillage/*/*.JPG')
label_list = [label_decoder[img_path.split('\\')[-2]] for img_path in img_list]

kfold = StratifiedKFold(n_splits=4, random_state=13, shuffle=True)
for idx, (kfold_train, kfold_val) in enumerate(kfold.split(img_list, label_list), 1) :
    print(idx, len(kfold_train), len(kfold_val))
    print(kfold_train)
    print(kfold_val)

1 15477 5159
[    1     2     3 ... 20632 20634 20635]
[    0    16    25 ... 20616 20630 20633]
2 15477 5159
[    0     1     3 ... 20633 20634 20635]
[    2     5    10 ... 20615 20617 20625]
3 15477 5159
[    0     1     2 ... 20633 20634 20635]
[    6    12    14 ... 20610 20622 20632]
4 15477 5159
[    0     2     5 ... 20630 20632 20633]
[    1     3     4 ... 20631 20634 20635]


# Plant Doc

### image 경로가 너무 길어서 읽어오지 못함.
- 이름을 0 ~ 1로 바꿈

In [43]:
img_name = glob('./data/public/PlantDoc/train/*.jpg')
len(img_name)

2328

In [44]:
with open('./data/public/PlantDoc/train/_classes.txt', 'r') as f :
    classese = f.readlines()

before_name = []
modi_name = []
for i in range(1, len(classese)) :
    split_name = classese[i].split(', ')[0]
    before_name.append(split_name)
    modi_name.append(f'{i}.jpg')
    classese[i] = classese[i].replace(split_name, f'{i}.jpg')
    

display(classese)
display(before_name)
display(modi_name)

['filename, Apple Scab Leaf, Apple leaf, Apple rust leaf, Bell_pepper leaf, Bell_pepper leaf spot, Blueberry leaf, Cherry leaf, Corn Gray leaf spot, Corn leaf blight, Corn rust leaf, Peach leaf, Potato leaf, Potato leaf early blight, Potato leaf late blight, Raspberry leaf, Soyabean leaf, Soybean leaf, Squash Powdery mildew leaf, Strawberry leaf, Tomato Early blight leaf, Tomato Septoria leaf spot, Tomato leaf, Tomato leaf bacterial spot, Tomato leaf late blight, Tomato leaf mosaic virus, Tomato leaf yellow virus, Tomato mold leaf, Tomato two spotted spider mites leaf, grape leaf, grape leaf black rot\n',
 '1.jpg, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0\n',
 '2.jpg, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0\n',
 '3.jpg, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0\n',
 '4.jpg, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

['2017-08-27%2B-%2BLate%2BBlight%2Bon%2BGypsy%2B1_jpg.rf.00584c9d14b6fda3086f9a482675d610.jpg',
 'Slide1_preview_jpg.rf.00f57cfc188631c10e10e2b93a38d296.jpg',
 'd-to-tylv-fo005-14496A31BE70553130A_jpg.rf.017e4558f1b4baeadc32a13beb178a6e.jpg',
 '2-3%20Gray%20leaf%20spot%20BRUCE_jpg.rf.0040c2e382cf11216938e6f49b7d65ed.jpg',
 'blueberry-leaf-isolated-white-background-blueberry-leaf-isolated-99227523_jpg.rf.00a825930e9396a34d6c3fc5cf86686e.jpg',
 'Apple-Scab-image-02_jpg.rf.00cbc9a108dbdaadf4232b5392e3d3c8.jpg',
 'Faske%20Southern%20rust%20of%20corn_jpg.rf.016116db58617610bb259b2965f41589.jpg',
 '14456_img_jpg.rf.0052b88d849e614c6037a2834800b4f8.jpg',
 '24154194959_fd4b42edde_b_jpg.rf.0012f9978a300c5635840700fa784280.jpg',
 'Septoria_tomato_Margaret%20B_p8170755_0002_25004_jpg.rf.00ddfef2668a53da256f207f9b844782.jpg',
 'DCDl_p8UQAAf2hP_jpg.rf.0192cb81cdbb3365925d7d47527de47a.jpg',
 'IMG_6029-001_1500x1500%253E_JPG?1403119544_jpg.rf.01aae68643601f970bad558834c627ae.jpg',
 '4-dogwood_pm_jpg.

['1.jpg',
 '2.jpg',
 '3.jpg',
 '4.jpg',
 '5.jpg',
 '6.jpg',
 '7.jpg',
 '8.jpg',
 '9.jpg',
 '10.jpg',
 '11.jpg',
 '12.jpg',
 '13.jpg',
 '14.jpg',
 '15.jpg',
 '16.jpg',
 '17.jpg',
 '18.jpg',
 '19.jpg',
 '20.jpg',
 '21.jpg',
 '22.jpg',
 '23.jpg',
 '24.jpg',
 '25.jpg',
 '26.jpg',
 '27.jpg',
 '28.jpg',
 '29.jpg',
 '30.jpg',
 '31.jpg',
 '32.jpg',
 '33.jpg',
 '34.jpg',
 '35.jpg',
 '36.jpg',
 '37.jpg',
 '38.jpg',
 '39.jpg',
 '40.jpg',
 '41.jpg',
 '42.jpg',
 '43.jpg',
 '44.jpg',
 '45.jpg',
 '46.jpg',
 '47.jpg',
 '48.jpg',
 '49.jpg',
 '50.jpg',
 '51.jpg',
 '52.jpg',
 '53.jpg',
 '54.jpg',
 '55.jpg',
 '56.jpg',
 '57.jpg',
 '58.jpg',
 '59.jpg',
 '60.jpg',
 '61.jpg',
 '62.jpg',
 '63.jpg',
 '64.jpg',
 '65.jpg',
 '66.jpg',
 '67.jpg',
 '68.jpg',
 '69.jpg',
 '70.jpg',
 '71.jpg',
 '72.jpg',
 '73.jpg',
 '74.jpg',
 '75.jpg',
 '76.jpg',
 '77.jpg',
 '78.jpg',
 '79.jpg',
 '80.jpg',
 '81.jpg',
 '82.jpg',
 '83.jpg',
 '84.jpg',
 '85.jpg',
 '86.jpg',
 '87.jpg',
 '88.jpg',
 '89.jpg',
 '90.jpg',
 '91.jpg',
 '92.jpg

### image 이름에 '?', ',' 있는거 제거

In [45]:
# with open('./data/public/PlantDoc/train/_classes.txt', 'r') as f :
#     classese = f.readlines()

# before_name = []
# modi_name = []
# for i in range(1, len(classese)) :
    
#     split_name = classese[i].split(', ')
    
#     if '?' in split_name[0] :
#         classese[i] = classese[i].replace(split_name[0], split_name[0].replace('?','_'))
        
#     if ',' in classese[i].split(', ')[0] :
#         before_name.append(split_name[0])
#         modi_name.append(split_name[0].replace(',',''))
#         classese[i] = classese[i].replace(before_name[-1], modi_name[-1])
        
#         print("@@@@@@@@@@@@@@@@@@")
#         print(before_name[-1])
#         print(modi_name[-1])
        

### 새로운 label txt 파일 생성

In [46]:
with open('./data/public/PlantDoc/train/_modi_classes.txt', 'w') as f :
    for data in classese:
        f.write(data)

### image 이름도 변경해주기

In [47]:
root_path = './data/public/PlantDoc/train'
img_list = glob(root_path+'/*.JPG')

for i in range(0, len(before_name)) :
    before_index = img_list.index(root_path+'\\'+before_name[i])
    img_list[before_index] = root_path+'\\'+modi_name[i]
    print(root_path+'\\'+before_name[i])
    print(root_path+'\\'+modi_name[i])
    print()
    
    os.rename(root_path+'\\'+before_name[i].replace('?','_'), root_path+'\\'+modi_name[i])

./data/public/PlantDoc/train\2017-08-27%2B-%2BLate%2BBlight%2Bon%2BGypsy%2B1_jpg.rf.00584c9d14b6fda3086f9a482675d610.jpg
./data/public/PlantDoc/train\1.jpg

./data/public/PlantDoc/train\Slide1_preview_jpg.rf.00f57cfc188631c10e10e2b93a38d296.jpg
./data/public/PlantDoc/train\2.jpg

./data/public/PlantDoc/train\d-to-tylv-fo005-14496A31BE70553130A_jpg.rf.017e4558f1b4baeadc32a13beb178a6e.jpg
./data/public/PlantDoc/train\3.jpg

./data/public/PlantDoc/train\2-3%20Gray%20leaf%20spot%20BRUCE_jpg.rf.0040c2e382cf11216938e6f49b7d65ed.jpg
./data/public/PlantDoc/train\4.jpg

./data/public/PlantDoc/train\blueberry-leaf-isolated-white-background-blueberry-leaf-isolated-99227523_jpg.rf.00a825930e9396a34d6c3fc5cf86686e.jpg
./data/public/PlantDoc/train\5.jpg

./data/public/PlantDoc/train\Apple-Scab-image-02_jpg.rf.00cbc9a108dbdaadf4232b5392e3d3c8.jpg
./data/public/PlantDoc/train\6.jpg

./data/public/PlantDoc/train\Faske%20Southern%20rust%20of%20corn_jpg.rf.016116db58617610bb259b2965f41589.jpg
./data/publ

ValueError: './data/public/PlantDoc/train\\IMG_6029-001_1500x1500%253E_JPG?1403119544_jpg.rf.01aae68643601f970bad558834c627ae.jpg' is not in list

In [38]:
root_path = './data/public/PlantDoc/train'
img_list = glob(root_path+'/*.JPG')

for i in range(0, len(before_name)) :
    before_index = img_list.index(root_path+'\\'+before_name[i])
    img_list[before_index] = root_path+'\\'+modi_name[i]
    print(root_path+'\\'+before_name[i])
    print(root_path+'\\'+modi_name[i])
    print()
    
    os.rename(root_path+'\\'+before_name[i], root_path+'\\'+modi_name[i])

./data/public/PlantDoc/train\2017-08-27%2B-%2BLate%2BBlight%2Bon%2BGypsy%2B1_jpg.rf.00584c9d14b6fda3086f9a482675d610.jpg
./data/public/PlantDoc/train\1.jpg

./data/public/PlantDoc/train\Slide1_preview_jpg.rf.00f57cfc188631c10e10e2b93a38d296.jpg
./data/public/PlantDoc/train\2.jpg

./data/public/PlantDoc/train\d-to-tylv-fo005-14496A31BE70553130A_jpg.rf.017e4558f1b4baeadc32a13beb178a6e.jpg
./data/public/PlantDoc/train\3.jpg

./data/public/PlantDoc/train\2-3%20Gray%20leaf%20spot%20BRUCE_jpg.rf.0040c2e382cf11216938e6f49b7d65ed.jpg
./data/public/PlantDoc/train\4.jpg

./data/public/PlantDoc/train\blueberry-leaf-isolated-white-background-blueberry-leaf-isolated-99227523_jpg.rf.00a825930e9396a34d6c3fc5cf86686e.jpg
./data/public/PlantDoc/train\5.jpg

./data/public/PlantDoc/train\Apple-Scab-image-02_jpg.rf.00cbc9a108dbdaadf4232b5392e3d3c8.jpg
./data/public/PlantDoc/train\6.jpg

./data/public/PlantDoc/train\Faske%20Southern%20rust%20of%20corn_jpg.rf.016116db58617610bb259b2965f41589.jpg
./data/publ

ValueError: './data/public/PlantDoc/train\\IMG_6029-001_1500x1500%253E_JPG?1403119544_jpg.rf.01aae68643601f970bad558834c627ae.jpg' is not in list

# data list 만들기
- none, 12, 17, 28번 클래스 삭제

In [11]:
import pandas as pd

label_csv = pd.read_csv('./data/public/PlantDoc/train/_modi_classes.txt')
columns_name = list(label_csv.columns)
columns_name.remove('filename')
columns_name.insert(0, 'None')

label_encoder = {idx : val.lstrip() for idx, val in enumerate(columns_name)}
label_decoder = {val : key for key, val in label_encoder.items()}
display(label_encoder)
display(label_decoder)

{0: 'None',
 1: 'Apple Scab Leaf',
 2: 'Apple leaf',
 3: 'Apple rust leaf',
 4: 'Bell_pepper leaf',
 5: 'Bell_pepper leaf spot',
 6: 'Blueberry leaf',
 7: 'Cherry leaf',
 8: 'Corn Gray leaf spot',
 9: 'Corn leaf blight',
 10: 'Corn rust leaf',
 11: 'Peach leaf',
 12: 'Potato leaf',
 13: 'Potato leaf early blight',
 14: 'Potato leaf late blight',
 15: 'Raspberry leaf',
 16: 'Soyabean leaf',
 17: 'Soybean leaf',
 18: 'Squash Powdery mildew leaf',
 19: 'Strawberry leaf',
 20: 'Tomato Early blight leaf',
 21: 'Tomato Septoria leaf spot',
 22: 'Tomato leaf',
 23: 'Tomato leaf bacterial spot',
 24: 'Tomato leaf late blight',
 25: 'Tomato leaf mosaic virus',
 26: 'Tomato leaf yellow virus',
 27: 'Tomato mold leaf',
 28: 'Tomato two spotted spider mites leaf',
 29: 'grape leaf',
 30: 'grape leaf black rot'}

{'None': 0,
 'Apple Scab Leaf': 1,
 'Apple leaf': 2,
 'Apple rust leaf': 3,
 'Bell_pepper leaf': 4,
 'Bell_pepper leaf spot': 5,
 'Blueberry leaf': 6,
 'Cherry leaf': 7,
 'Corn Gray leaf spot': 8,
 'Corn leaf blight': 9,
 'Corn rust leaf': 10,
 'Peach leaf': 11,
 'Potato leaf': 12,
 'Potato leaf early blight': 13,
 'Potato leaf late blight': 14,
 'Raspberry leaf': 15,
 'Soyabean leaf': 16,
 'Soybean leaf': 17,
 'Squash Powdery mildew leaf': 18,
 'Strawberry leaf': 19,
 'Tomato Early blight leaf': 20,
 'Tomato Septoria leaf spot': 21,
 'Tomato leaf': 22,
 'Tomato leaf bacterial spot': 23,
 'Tomato leaf late blight': 24,
 'Tomato leaf mosaic virus': 25,
 'Tomato leaf yellow virus': 26,
 'Tomato mold leaf': 27,
 'Tomato two spotted spider mites leaf': 28,
 'grape leaf': 29,
 'grape leaf black rot': 30}

In [12]:
root_path = './data/public/PlantDoc/train'

with open('./data/public/PlantDoc/train/_modi_classes.txt', 'r') as f :
    classese = f.readlines()

label_list = []
img_list = []
for i in range(1, len(classese)) :
    img_list.append(root_path + '/' + classese[i].split(', ')[0])
    if '1' in classese[i].split(', ') :
        label_list.append(classese[i].split(', ').index('1'))
    elif '1\n' in classese[i].split(', ') :
        label_list.append(classese[i].split(', ').index('1\n'))
    else : 
        label_list.append(0)

print(img_list)
print(label_list)

['./data/public/PlantDoc/train/2017-08-27%2B-%2BLate%2BBlight%2Bon%2BGypsy%2B1_jpg.rf.00584c9d14b6fda3086f9a482675d610.jpg', './data/public/PlantDoc/train/Slide1_preview_jpg.rf.00f57cfc188631c10e10e2b93a38d296.jpg', './data/public/PlantDoc/train/d-to-tylv-fo005-14496A31BE70553130A_jpg.rf.017e4558f1b4baeadc32a13beb178a6e.jpg', './data/public/PlantDoc/train/2-3%20Gray%20leaf%20spot%20BRUCE_jpg.rf.0040c2e382cf11216938e6f49b7d65ed.jpg', './data/public/PlantDoc/train/blueberry-leaf-isolated-white-background-blueberry-leaf-isolated-99227523_jpg.rf.00a825930e9396a34d6c3fc5cf86686e.jpg', './data/public/PlantDoc/train/Apple-Scab-image-02_jpg.rf.00cbc9a108dbdaadf4232b5392e3d3c8.jpg', './data/public/PlantDoc/train/Faske%20Southern%20rust%20of%20corn_jpg.rf.016116db58617610bb259b2965f41589.jpg', './data/public/PlantDoc/train/14456_img_jpg.rf.0052b88d849e614c6037a2834800b4f8.jpg', './data/public/PlantDoc/train/24154194959_fd4b42edde_b_jpg.rf.0012f9978a300c5635840700fa784280.jpg', './data/public/Pla

# class 별 갯수
- 10개 이하 class는 삭제 해줌
- 삭제해야할 label - 0, 12, 17, 28 

In [13]:
root_path = './data/public/PlantDoc/train'

with open('./data/public/PlantDoc/train/_modi_classes.txt', 'r') as f :
    classese = f.readlines()

label_list = []
img_list = []
for i in range(1, len(classese)) :
    img_list.append(root_path + '/' + classese[i].split(', ')[0])
    if '1' in classese[i].split(', ') :
        label_list.append(classese[i].split(', ').index('1'))
    elif '1\n' in classese[i].split(', ') :
        label_list.append(classese[i].split(', ').index('1\n'))
    else : 
        label_list.append(0)
label_cnt = {k : 0 for k, v in label_decoder.items()}

for i in label_list :
    label_cnt[label_encoder[i]] += 1

display(label_cnt)

{'None': 10,
 'Apple Scab Leaf': 83,
 'Apple leaf': 82,
 'Apple rust leaf': 78,
 'Bell_pepper leaf': 53,
 'Bell_pepper leaf spot': 62,
 'Blueberry leaf': 103,
 'Cherry leaf': 47,
 'Corn Gray leaf spot': 61,
 'Corn leaf blight': 178,
 'Corn rust leaf': 106,
 'Peach leaf': 101,
 'Potato leaf': 3,
 'Potato leaf early blight': 103,
 'Potato leaf late blight': 94,
 'Raspberry leaf': 112,
 'Soyabean leaf': 57,
 'Soybean leaf': 1,
 'Squash Powdery mildew leaf': 124,
 'Strawberry leaf': 87,
 'Tomato Early blight leaf': 79,
 'Tomato Septoria leaf spot': 137,
 'Tomato leaf': 56,
 'Tomato leaf bacterial spot': 101,
 'Tomato leaf late blight': 99,
 'Tomato leaf mosaic virus': 44,
 'Tomato leaf yellow virus': 68,
 'Tomato mold leaf': 86,
 'Tomato two spotted spider mites leaf': 0,
 'grape leaf': 57,
 'grape leaf black rot': 56}

### class 삭제

In [14]:
label_cnt_ = {label_decoder[k] : v for k, v in label_cnt.items()}
display(label_cnt_)
remove_list = []
for k, v in label_cnt_.items() :
    for i in range(0, len(label_list)) :
        if label_list[i] == k and v <= 10 :
            remove_list.append(i)
            print(label_list[i])
            print(img_list[i])
            
display(remove_list)
remove_list.sort(reverse=True)
display(remove_list)

print(len(img_list))
print(len(label_list))
for remove_num in remove_list :
    del img_list[remove_num]
    del label_list[remove_num]

print(len(img_list))
print(len(label_list))


### 0, 12, 17, 28 삭제해야할 label

{0: 10,
 1: 83,
 2: 82,
 3: 78,
 4: 53,
 5: 62,
 6: 103,
 7: 47,
 8: 61,
 9: 178,
 10: 106,
 11: 101,
 12: 3,
 13: 103,
 14: 94,
 15: 112,
 16: 57,
 17: 1,
 18: 124,
 19: 87,
 20: 79,
 21: 137,
 22: 56,
 23: 101,
 24: 99,
 25: 44,
 26: 68,
 27: 86,
 28: 0,
 29: 57,
 30: 56}

0
./data/public/PlantDoc/train/270412tglr-wild-strawberry-flowers-and-leaf-patch_jpg.rf.11e3d6fa8e0828ac716e6e40f92ebd6b.jpg
0
./data/public/PlantDoc/train/Hydrangea+%2527Claudie%2527%252C+Powdery+Mildew_JPG_jpg.rf.241a2ba81fae4dd8f4d42a639bf4c542.jpg
0
./data/public/PlantDoc/train/tomato_D4a-TobRingspotVirus-1000077_zoom_jpg.rf.2e3bf56fca79319caad79756a5a3489f.jpg
0
./data/public/PlantDoc/train/Downy%20mildew_JPG_jpg.rf.5cd0d81448f536b690c687fe43801ad8.jpg
0
./data/public/PlantDoc/train/raspberries_jpg.rf.6f265fc0cc6e20357544cda8c1e08794.jpg
0
./data/public/PlantDoc/train/powdery-mildew-erysiphe-plantani-on-young-sycamore-leaf-b372wn_jpg.rf.9f2fd157b98d7080ee62fda831e913e9.jpg
0
./data/public/PlantDoc/train/Black+Raspberry+Leaves+3_jpg.rf.a5118930e06e0d086213803cfdda04b3.jpg
0
./data/public/PlantDoc/train/raspberry-db_jpg.rf.b3eabfd7a40d314ed0bd68e867f3bf6b.jpg
0
./data/public/PlantDoc/train/aquilegia-powdery-mildew-erysiphe-aquilegiae-on-columbine-leaves-bga5xr_jpg.rf.bd049474ad6eb0e

[151, 324, 415, 827, 996, 1433, 1500, 1629, 1717, 1847, 1471, 1706, 1916, 36]

[1916, 1847, 1717, 1706, 1629, 1500, 1471, 1433, 996, 827, 415, 324, 151, 36]

2328
2328
2314
2314


### 삭제된 라벨만큼 라벨 번호 당기기

In [15]:
for i in range(0, len(label_list)) :
    print(label_list[i])
    if label_list[i] > 0 and label_list[i] < 12 :
        label_list[i] -= 1
    elif label_list[i] > 12 and label_list[i] < 17 :
        label_list[i] -= 2
    elif label_list[i] > 17 and label_list[i] < 28 :
        label_list[i] -= 3
    elif label_list[i] > 28 :
        label_list[i] -= 4
    print(label_list[i])
    print()

24
21

9
8

27
24

9
8

6
5

1
0

10
9

26
23

9
8

21
18

30
26

5
4

5
4

9
8

4
3

5
4

1
0

13
11

23
20

3
2

15
13

25
22

9
8

18
15

14
12

18
15

9
8

20
17

9
8

13
11

14
12

20
17

21
18

20
17

24
21

11
10

16
14

1
0

8
7

15
13

26
23

27
24

18
15

23
20

15
13

20
17

2
1

18
15

6
5

24
21

10
9

18
15

3
2

19
16

18
15

11
10

26
23

11
10

27
24

13
11

1
0

7
6

3
2

2
1

15
13

26
23

14
12

19
16

21
18

13
11

20
17

14
12

25
22

15
13

23
20

26
23

24
21

25
22

6
5

11
10

6
5

2
1

1
0

15
13

15
13

1
0

14
12

6
5

10
9

15
13

14
12

18
15

16
14

14
12

2
1

6
5

21
18

26
23

13
11

15
13

22
19

16
14

13
11

21
18

13
11

18
15

21
18

25
22

19
16

16
14

21
18

21
18

6
5

24
21

16
14

9
8

9
8

9
8

3
2

26
23

18
15

11
10

13
11

30
26

13
11

10
9

9
8

6
5

11
10

8
7

21
18

5
4

23
20

2
1

15
13

24
21

26
23

30
26

24
21

18
15

4
3

27
24

14
12

26
23

7
6

6
5

13
11

9
8

18
15

6
5

26
23

2
1

9
8

27
24

8
7

14
12

27
24

1
0




29
25

15
13

8
7

24
21

11
10

26
23

27
24

25
22

9
8

18
15

5
4

3
2

23
20

29
25

5
4

19
16

15
13

19
16

27
24

23
20

10
9

9
8

23
20

21
18

5
4

22
19

19
16

29
25

10
9

21
18

29
25

14
12

8
7

4
3

21
18

9
8

18
15

21
18

10
9

3
2

15
13

6
5

3
2

2
1

24
21

6
5

13
11

26
23

1
0

18
15

9
8

4
3

19
16

6
5

3
2

3
2

15
13

3
2

18
15

11
10

27
24

13
11

13
11

11
10

22
19

18
15

5
4

26
23

8
7

27
24

29
25

23
20

10
9

10
9

11
10

6
5

7
6

4
3

27
24

25
22

18
15

14
12

20
17

21
18

1
0

29
25

7
6

3
2

27
24

3
2

6
5

20
17

24
21

13
11

11
10

3
2

8
7

9
8

27
24

5
4

14
12

4
3

30
26

7
6

1
0

30
26

24
21

3
2

18
15

9
8

25
22

11
10

19
16

14
12

18
15

9
8

20
17

30
26

26
23

18
15

23
20

5
4

18
15

20
17

18
15

15
13

7
6

14
12

18
15

14
12

9
8

1
0

10
9

4
3

16
14

11
10

6
5

13
11

18
15

22
19

18
15

26
23

15
13

14
12

4
3

15
13

21
18

10
9

23
20

16
14

14
12

6
5

20
17

23
20

5
4

2
1

4
3

26
23

20
17


### label_decoder encoder 재선언

In [16]:
import pandas as pd

label_csv = pd.read_csv('./data/public/PlantDoc/train/_modi_classes.txt')
columns_name = list(label_csv.columns)
columns_name.remove('filename')
columns_name.remove(' Potato leaf') # 12
columns_name.remove(' Soybean leaf') # 17
columns_name.remove(' Tomato two spotted spider mites leaf') # 28

label_encoder = {idx : val.lstrip() for idx, val in enumerate(columns_name)}
label_decoder = {val : key for key, val in label_encoder.items()}
display(label_encoder)
display(label_decoder)

{0: 'Apple Scab Leaf',
 1: 'Apple leaf',
 2: 'Apple rust leaf',
 3: 'Bell_pepper leaf',
 4: 'Bell_pepper leaf spot',
 5: 'Blueberry leaf',
 6: 'Cherry leaf',
 7: 'Corn Gray leaf spot',
 8: 'Corn leaf blight',
 9: 'Corn rust leaf',
 10: 'Peach leaf',
 11: 'Potato leaf early blight',
 12: 'Potato leaf late blight',
 13: 'Raspberry leaf',
 14: 'Soyabean leaf',
 15: 'Squash Powdery mildew leaf',
 16: 'Strawberry leaf',
 17: 'Tomato Early blight leaf',
 18: 'Tomato Septoria leaf spot',
 19: 'Tomato leaf',
 20: 'Tomato leaf bacterial spot',
 21: 'Tomato leaf late blight',
 22: 'Tomato leaf mosaic virus',
 23: 'Tomato leaf yellow virus',
 24: 'Tomato mold leaf',
 25: 'grape leaf',
 26: 'grape leaf black rot'}

{'Apple Scab Leaf': 0,
 'Apple leaf': 1,
 'Apple rust leaf': 2,
 'Bell_pepper leaf': 3,
 'Bell_pepper leaf spot': 4,
 'Blueberry leaf': 5,
 'Cherry leaf': 6,
 'Corn Gray leaf spot': 7,
 'Corn leaf blight': 8,
 'Corn rust leaf': 9,
 'Peach leaf': 10,
 'Potato leaf early blight': 11,
 'Potato leaf late blight': 12,
 'Raspberry leaf': 13,
 'Soyabean leaf': 14,
 'Squash Powdery mildew leaf': 15,
 'Strawberry leaf': 16,
 'Tomato Early blight leaf': 17,
 'Tomato Septoria leaf spot': 18,
 'Tomato leaf': 19,
 'Tomato leaf bacterial spot': 20,
 'Tomato leaf late blight': 21,
 'Tomato leaf mosaic virus': 22,
 'Tomato leaf yellow virus': 23,
 'Tomato mold leaf': 24,
 'grape leaf': 25,
 'grape leaf black rot': 26}

### 라벨 카운트

In [5]:
label_cnt = {k : 0 for k, v in label_decoder.items()}

for i in label_list :
    label_cnt[label_encoder[i]] += 1

display(label_cnt)

{'Apple___Apple_scab': 630,
 'Apple___Black_rot': 621,
 'Apple___Cedar_apple_rust': 275,
 'Apple___healthy': 1645,
 'Blueberry___healthy': 1502,
 'Cherry_(including_sour)___healthy': 854,
 'Cherry_(including_sour)___Powdery_mildew': 1052,
 'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot': 513,
 'Corn_(maize)___Common_rust_': 1192,
 'Corn_(maize)___healthy': 1162,
 'Corn_(maize)___Northern_Leaf_Blight': 985,
 'Grape___Black_rot': 1180,
 'Grape___Esca_(Black_Measles)': 1383,
 'Grape___healthy': 423,
 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)': 1076,
 'Orange___Haunglongbing_(Citrus_greening)': 5507,
 'Peach___Bacterial_spot': 2297,
 'Peach___healthy': 360,
 'Pepper,_bell___Bacterial_spot': 997,
 'Pepper,_bell___healthy': 1477,
 'Potato___Early_blight': 1000,
 'Potato___healthy': 152,
 'Potato___Late_blight': 1000,
 'Raspberry___healthy': 371,
 'Soybean___healthy': 5090,
 'Squash___Powdery_mildew': 1835,
 'Strawberry___healthy': 456,
 'Strawberry___Leaf_scorch': 1109,
 'Tomato___Bac

# Custom dataset 정의

In [18]:
class DocDataset(Dataset) :
    def __init__(self, imgs, labels, transform) :
        super(VillageDataset, self).__init__()
        self.imgs = imgs
        self.labels = labels
        self.transform = transform
        
    def __len__(self) :
        assert len(self.imgs) == len(self.labels)
        return len(self.imgs)
    
    def __getitem__(self, idx) :
        
        label = self.labels[idx]
        
        img = cv2.imread(self.imgs[idx])
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        img = self.transform(image=img)['image']
        img = img.transpose(2, 0, 1)
        
        return torch.tensor(img, dtype=torch.float32), torch.tensor(label, dtype=torch.long)

# DataLoader w/o kfold

In [19]:
train_transforms = A.Compose([
                A.Resize(224 ,224),
                A.OneOf([
                    A.Rotate(),
                    A.HorizontalFlip(),
                    A.VerticalFlip()
                ], p=1)
            ])

val_transforms = A.Compose([
    A.Resize(224,224)
])


train_img, val_img, train_label, val_label = train_test_split(img_list, label_list, test_size=0.3, shuffle=True, stratify=label_list)

print("train_img : ", len(train_img))
print("train_lable : ", len(train_label))

print("val_img : ", len(val_img))
print("val_lable : ", len(val_label))

print(train_img[572])
print(train_label[572])

# train_dataset = VillageDataset(train, train_transforms)
# val_dataset = VillageDataset(val, val_transforms)

# train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
# val_loader = DataLoader(val_dataset, batch_size=16, shuffle=False)

train_img :  1619
train_lable :  1619
val_img :  695
val_lable :  695
./data/public/PlantDoc/train/potato-early-blight-alternaria-alternata-target-spot-lesion-on-a-potato-leaf-x63fwh_jpg.rf.4bc8edaa7926474ba7a3d757f7aca91c.jpg
11


# Doc +Village = 라벨 합치기
- Doc == Village
- 11: 'Potato leaf early blight', ==  2: 'Potato___Early_blight',
- 12: 'Potato leaf late blight', ==  4: 'Potato___Late_blight',
- 17: 'Tomato Early blight leaf', ==  6: 'Tomato_Early_blight',
- 18: 'Tomato Septoria leaf spot', ==  10: 'Tomato_Septoria_leaf_spot',
- 19: 'Tomato leaf', ==  7: 'Tomato_healthy',
- 20: 'Tomato leaf bacterial spot', ==  5: 'Tomato_Bacterial_spot',
- 21: 'Tomato leaf late blight', ==  8: 'Tomato_Late_blight',
- 22: 'Tomato leaf mosaic virus', ==  13: 'Tomato__Tomato_mosaic_virus',
- 23: 'Tomato leaf yellow virus', ==  14: 'Tomato__Tomato_YellowLeaf__Curl_Virus'

## Village img, label data

In [20]:
village_data = os.listdir('./data/public/PlantVillage')
vill_label_encoder = {}
for idx, data_name in enumerate(village_data) :
    vill_label_encoder[idx] = data_name

vill_label_decoder = {val:key for key, val in vill_label_encoder.items()}
display(vill_label_decoder)
display(vill_label_encoder)

vill_img_list = glob('./data/public/PlantVillage/*/*.JPG')
vill_label_list = [vill_label_decoder[img_path.split('\\')[-2]] for img_path in vill_img_list]

print(len(vill_img_list))
print(len(vill_label_list))

{'Pepper__bell___Bacterial_spot': 0,
 'Pepper__bell___healthy': 1,
 'Potato___Early_blight': 2,
 'Potato___healthy': 3,
 'Potato___Late_blight': 4,
 'Tomato_Bacterial_spot': 5,
 'Tomato_Early_blight': 6,
 'Tomato_healthy': 7,
 'Tomato_Late_blight': 8,
 'Tomato_Leaf_Mold': 9,
 'Tomato_Septoria_leaf_spot': 10,
 'Tomato_Spider_mites_Two_spotted_spider_mite': 11,
 'Tomato__Target_Spot': 12,
 'Tomato__Tomato_mosaic_virus': 13,
 'Tomato__Tomato_YellowLeaf__Curl_Virus': 14}

{0: 'Pepper__bell___Bacterial_spot',
 1: 'Pepper__bell___healthy',
 2: 'Potato___Early_blight',
 3: 'Potato___healthy',
 4: 'Potato___Late_blight',
 5: 'Tomato_Bacterial_spot',
 6: 'Tomato_Early_blight',
 7: 'Tomato_healthy',
 8: 'Tomato_Late_blight',
 9: 'Tomato_Leaf_Mold',
 10: 'Tomato_Septoria_leaf_spot',
 11: 'Tomato_Spider_mites_Two_spotted_spider_mite',
 12: 'Tomato__Target_Spot',
 13: 'Tomato__Tomato_mosaic_virus',
 14: 'Tomato__Tomato_YellowLeaf__Curl_Virus'}

20636
20636


## Doc img, label data

In [21]:
import copy
doc_img_list = copy.deepcopy(img_list)
doc_label_list = copy.deepcopy(label_list)

doc_label_decoder = copy.deepcopy(label_decoder) 
doc_label_encoder = copy.deepcopy(label_encoder)

display(doc_label_decoder)
display(doc_label_encoder)
print(len(doc_img_list))
print(len(doc_label_list))

{'Apple Scab Leaf': 0,
 'Apple leaf': 1,
 'Apple rust leaf': 2,
 'Bell_pepper leaf': 3,
 'Bell_pepper leaf spot': 4,
 'Blueberry leaf': 5,
 'Cherry leaf': 6,
 'Corn Gray leaf spot': 7,
 'Corn leaf blight': 8,
 'Corn rust leaf': 9,
 'Peach leaf': 10,
 'Potato leaf early blight': 11,
 'Potato leaf late blight': 12,
 'Raspberry leaf': 13,
 'Soyabean leaf': 14,
 'Squash Powdery mildew leaf': 15,
 'Strawberry leaf': 16,
 'Tomato Early blight leaf': 17,
 'Tomato Septoria leaf spot': 18,
 'Tomato leaf': 19,
 'Tomato leaf bacterial spot': 20,
 'Tomato leaf late blight': 21,
 'Tomato leaf mosaic virus': 22,
 'Tomato leaf yellow virus': 23,
 'Tomato mold leaf': 24,
 'grape leaf': 25,
 'grape leaf black rot': 26}

{0: 'Apple Scab Leaf',
 1: 'Apple leaf',
 2: 'Apple rust leaf',
 3: 'Bell_pepper leaf',
 4: 'Bell_pepper leaf spot',
 5: 'Blueberry leaf',
 6: 'Cherry leaf',
 7: 'Corn Gray leaf spot',
 8: 'Corn leaf blight',
 9: 'Corn rust leaf',
 10: 'Peach leaf',
 11: 'Potato leaf early blight',
 12: 'Potato leaf late blight',
 13: 'Raspberry leaf',
 14: 'Soyabean leaf',
 15: 'Squash Powdery mildew leaf',
 16: 'Strawberry leaf',
 17: 'Tomato Early blight leaf',
 18: 'Tomato Septoria leaf spot',
 19: 'Tomato leaf',
 20: 'Tomato leaf bacterial spot',
 21: 'Tomato leaf late blight',
 22: 'Tomato leaf mosaic virus',
 23: 'Tomato leaf yellow virus',
 24: 'Tomato mold leaf',
 25: 'grape leaf',
 26: 'grape leaf black rot'}

2314
2314


## Village -> Doc

### Village Label 번호 변경

In [22]:
 # {vill : doc}
same_label_list_encoder = {0:27, 1:28, 2:11, 3:29, 4:12, 5:20, 6:17, 7:19, 8:21, 9:30, 10:18, 11:31, 12:32, 13:22, 14:23}
for i in range(0, len(vill_label_list)) :
    vill_label_list[i] = same_label_list_encoder[vill_label_list[i]]

## add

In [23]:
sum_img_list = doc_img_list + vill_img_list
sum_label_list = doc_label_list + vill_label_list

print(len(sum_img_list))
print(len(sum_label_list))

22950
22950


## sum_label_encoder decoder 선언

In [24]:
same_label_list_encoder = {0:27, 1:28, 2:11, 3:29, 4:12, 5:20, 6:17, 7:19, 8:21, 9:30, 10:18, 11:31, 12:32, 13:22, 14:23}
same_label_list_decoder = {v : k for k, v in same_label_list_encoder.items()}

additional_list = [0, 1, 3, 9, 11, 12]

sum_label_encoder = {}
for i in range(0, 33) :
    if i in same_label_list_decoder and i in doc_label_encoder :
        sum_label_encoder[i] = doc_label_encoder[i]
#         sum_label_encoder[vill_label_encoder[i]] = same_label_list_encoder[i]

    elif i in same_label_list_decoder and i not in doc_label_encoder :
        sum_label_encoder[i] = vill_label_encoder[same_label_list_decoder[i]]
#         sum_label_encoder[doc_label_encoder[i]] = same_label_list_encoder[i]
        
    elif i not in same_label_list_decoder and i in doc_label_encoder :
        sum_label_encoder[i] = doc_label_encoder[i]
        
sum_label_decoder = {v : k for k, v in sum_label_encoder.items()}

display(sum_label_encoder)
display(sum_label_decoder)

{0: 'Apple Scab Leaf',
 1: 'Apple leaf',
 2: 'Apple rust leaf',
 3: 'Bell_pepper leaf',
 4: 'Bell_pepper leaf spot',
 5: 'Blueberry leaf',
 6: 'Cherry leaf',
 7: 'Corn Gray leaf spot',
 8: 'Corn leaf blight',
 9: 'Corn rust leaf',
 10: 'Peach leaf',
 11: 'Potato leaf early blight',
 12: 'Potato leaf late blight',
 13: 'Raspberry leaf',
 14: 'Soyabean leaf',
 15: 'Squash Powdery mildew leaf',
 16: 'Strawberry leaf',
 17: 'Tomato Early blight leaf',
 18: 'Tomato Septoria leaf spot',
 19: 'Tomato leaf',
 20: 'Tomato leaf bacterial spot',
 21: 'Tomato leaf late blight',
 22: 'Tomato leaf mosaic virus',
 23: 'Tomato leaf yellow virus',
 24: 'Tomato mold leaf',
 25: 'grape leaf',
 26: 'grape leaf black rot',
 27: 'Pepper__bell___Bacterial_spot',
 28: 'Pepper__bell___healthy',
 29: 'Potato___healthy',
 30: 'Tomato_Leaf_Mold',
 31: 'Tomato_Spider_mites_Two_spotted_spider_mite',
 32: 'Tomato__Target_Spot'}

{'Apple Scab Leaf': 0,
 'Apple leaf': 1,
 'Apple rust leaf': 2,
 'Bell_pepper leaf': 3,
 'Bell_pepper leaf spot': 4,
 'Blueberry leaf': 5,
 'Cherry leaf': 6,
 'Corn Gray leaf spot': 7,
 'Corn leaf blight': 8,
 'Corn rust leaf': 9,
 'Peach leaf': 10,
 'Potato leaf early blight': 11,
 'Potato leaf late blight': 12,
 'Raspberry leaf': 13,
 'Soyabean leaf': 14,
 'Squash Powdery mildew leaf': 15,
 'Strawberry leaf': 16,
 'Tomato Early blight leaf': 17,
 'Tomato Septoria leaf spot': 18,
 'Tomato leaf': 19,
 'Tomato leaf bacterial spot': 20,
 'Tomato leaf late blight': 21,
 'Tomato leaf mosaic virus': 22,
 'Tomato leaf yellow virus': 23,
 'Tomato mold leaf': 24,
 'grape leaf': 25,
 'grape leaf black rot': 26,
 'Pepper__bell___Bacterial_spot': 27,
 'Pepper__bell___healthy': 28,
 'Potato___healthy': 29,
 'Tomato_Leaf_Mold': 30,
 'Tomato_Spider_mites_Two_spotted_spider_mite': 31,
 'Tomato__Target_Spot': 32}

# === Village Dataset으로만 훈련 ===

### Cutmix

In [25]:
def rand_bbox(size, lam):
    W = size[2]
    H = size[3]
    cut_rat = np.sqrt(1. - lam)
    cut_w = np.int(W * cut_rat)
    cut_h = np.int(H * cut_rat)
 
    # uniform
    cx = np.random.randint(W)
    cy = np.random.randint(H)

    bbx1 = np.clip(cx - cut_w // 2, 0, W)
    bby1 = np.clip(cy - cut_h // 2, 0, H)
    bbx2 = np.clip(cx + cut_w // 2, 0, W)
    bby2 = np.clip(cy + cut_h // 2, 0, H)

    return bbx1, bby1, bbx2, bby2

### Model

In [26]:
import timm

class DeiT(nn.Module):
    def __init__(self, model_name, n_classes):
        super(DeiT, self).__init__()
        self.model = timm.create_model(model_name, num_classes=n_classes, pretrained=True)
    
    def forward(self, inputs):
        output = self.model(inputs)
        return output

In [27]:
def accuracy_function(real, pred):    
    real = real.cpu()
    pred = torch.argmax(pred, dim=1).cpu()
    score = f1_score(real, pred, average='macro')
    return score

def train_step(batch_item, training):
    img = batch_item[0].to(device)
    label = batch_item[1].to(device)
    print("img")
    print(img.shape)
    lam = np.random.beta(1.0, 1.0)
    
    if training is True:
        model.train()
        optimizer.zero_grad()
        with torch.cuda.amp.autocast():
            # add - cutmix
            rand_index = torch.randperm(img.size()[0])
            target_a = label
            target_b = label[rand_index]
            bbx1, bby1, bbx2, bby2 = rand_bbox(img.size(), lam)
            img[:, :, bbx1:bbx2, bby1:bby2] = img[rand_index, :, bbx1:bbx2, bby1:bby2]
            lam = 1 - ((bbx2 - bbx1) * (bby2 - bby1) / (img.size()[-1] * img.size()[-2]))
            
            output = model(img)
            loss = criterion(output, target_a) * lam + criterion(output, target_b) * (1. - lam)
            
#             output = model(img, csv_feature)
#             loss = criterion(output, label)
        loss.backward()
        optimizer.step()
        score = accuracy_function(label, output)
        return loss, score
    else:
        model.eval()
        with torch.no_grad():
            output = model(img)
            loss = criterion(output, label)
        score = accuracy_function(label, output)
        return loss, score

In [28]:
device = torch.device("cuda:0")#("cpu")
batch_size = 16
n_classes = 33
model_name = 'deit_small_patch16_224'
learning_rate = 1e-4
epochs = 20
save_path = 'public_vill_doc_pretrain_Deit_S16patch224.pt'

# Custom dataset 정의

In [29]:
class CombineDataset(Dataset) :
    def __init__(self, imgs, labels, transform) :
        super(CombineDataset, self).__init__()
        self.imgs = imgs
        self.labels = labels
        self.transform = transform
        
    def __len__(self) :
        assert len(self.imgs) == len(self.labels)
        return len(self.imgs)
    
    def __getitem__(self, idx) :
        
        label = self.labels[idx]
        
        img = cv2.imread(self.imgs[idx])
        print("???")
        print(img)
        print(self.imgs[idx])
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        img = self.transform(image=img)['image']
        img = img.transpose(2, 0, 1)
        
        return torch.tensor(img, dtype=torch.float32)/255.0, torch.tensor(label, dtype=torch.long)

# DataLoader w/o kfold

In [30]:
train_transforms = A.Compose([
                A.Resize(224 ,224),
                A.OneOf([
                    A.Rotate(),
                    A.HorizontalFlip(),
                    A.VerticalFlip()
                ], p=1)
            ])

val_transforms = A.Compose([
    A.Resize(224,224)
])


print(len(sum_img_list))
print(len(sum_label_list))

train_img, val_img, train_label, val_label = train_test_split(sum_img_list, 
                                                              sum_label_list, 
                                                              test_size=0.2, 
                                                              shuffle=True, 
                                                              stratify=sum_label_list)

print("train_img : ", len(train_img))
print("train_lable : ", len(train_label))

print("val_img : ", len(val_img))
print("val_lable : ", len(val_label))

print(train_img[572])
print(train_label[572])

train_dataset = CombineDataset(train_img, train_label, train_transforms)
val_dataset = CombineDataset(val_img, val_label, val_transforms)

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)

22950
22950
train_img :  18360
train_lable :  18360
val_img :  4590
val_lable :  4590
./data/public/PlantVillage\Tomato_Spider_mites_Two_spotted_spider_mite\77d5f7bf-a888-43f2-8403-82a01a10bf12___Com.G_SpM_FL 9579.JPG
31


In [32]:
model = DeiT(model_name, n_classes)
model = model.to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
criterion = nn.CrossEntropyLoss()

In [33]:
loss_plot, val_loss_plot = [], []
metric_plot, val_metric_plot = [], []

for epoch in range(epochs):
    total_loss, total_val_loss = 0, 0
    total_acc, total_val_acc = 0, 0

    tqdm_dataset = tqdm(enumerate(train_loader))
    training = True
    for batch, batch_item in tqdm_dataset:
        batch_loss, batch_acc = train_step(batch_item, training)
        total_loss += batch_loss
        total_acc += batch_acc

        tqdm_dataset.set_postfix({
            'Epoch': epoch + 1,
            'Loss': '{:06f}'.format(batch_loss.item()),
            'Mean Loss' : '{:06f}'.format(total_loss/(batch+1)),
            'Mean F-1' : '{:06f}'.format(total_acc/(batch+1))
        })
    loss_plot.append(total_loss/(batch+1))
    metric_plot.append(total_acc/(batch+1))

    tqdm_dataset = tqdm(enumerate(val_loader))
    training = False
    for batch, batch_item in tqdm_dataset:
        batch_loss, batch_acc = train_step(batch_item, training)
        total_val_loss += batch_loss
        total_val_acc += batch_acc

        tqdm_dataset.set_postfix({
            'Epoch': epoch + 1,
            'Val Loss': '{:06f}'.format(batch_loss.item()),
            'Mean Val Loss' : '{:06f}'.format(total_val_loss/(batch+1)),
            'Mean Val F-1' : '{:06f}'.format(total_val_acc/(batch+1))
        })
    val_loss_plot.append(total_val_loss/(batch+1))
    val_metric_plot.append(total_val_acc/(batch+1))

    if np.max(val_metric_plot) == val_metric_plot[-1]:
        torch.save(model.state_dict(), f'{epoch}_{save_path}')

0it [00:00, ?it/s]

???
[[[138 132 151]
  [115 109 128]
  [136 130 149]
  ...
  [115 109 128]
  [134 128 147]
  [134 128 147]]

 [[150 144 163]
  [131 125 144]
  [147 141 160]
  ...
  [124 118 137]
  [160 154 173]
  [150 144 163]]

 [[132 126 145]
  [124 118 137]
  [145 139 158]
  ...
  [116 110 129]
  [103  97 116]
  [117 111 130]]

 ...

 [[162 152 168]
  [164 154 170]
  [167 157 173]
  ...
  [159 149 165]
  [148 138 154]
  [172 162 178]]

 [[154 144 160]
  [161 151 167]
  [156 146 162]
  ...
  [141 131 147]
  [142 132 148]
  [176 166 182]]

 [[170 160 176]
  [162 152 168]
  [150 140 156]
  ...
  [157 147 163]
  [148 138 154]
  [149 139 155]]]
./data/public/PlantVillage\Potato___healthy\af15ac00-67ff-4114-ace8-6dca48b94665___RS_HL 1865.JPG
???
[[[181 165 176]
  [171 155 166]
  [196 181 189]
  ...
  [189 179 191]
  [161 151 163]
  [158 148 160]]

 [[184 168 179]
  [183 167 178]
  [210 195 203]
  ...
  [157 147 159]
  [169 159 171]
  [153 143 155]]

 [[192 177 185]
  [201 186 194]
  [187 174 182]
  ...
  

1it [00:01,  1.39s/it, Epoch=1, Loss=3.763376, Mean Loss=3.763376, Mean F-1=0.000000]

???
[[[ 90  86  85]
  [ 91  87  86]
  [ 91  87  86]
  ...
  [128 127 131]
  [135 134 138]
  [131 130 134]]

 [[ 84  80  79]
  [ 83  79  78]
  [ 86  82  81]
  ...
  [131 130 134]
  [123 122 126]
  [123 122 126]]

 [[ 88  84  83]
  [ 85  81  80]
  [ 89  85  84]
  ...
  [139 138 142]
  [123 122 126]
  [129 128 132]]

 ...

 [[ 48  48  48]
  [ 51  51  51]
  [ 53  53  53]
  ...
  [113 116 121]
  [111 114 119]
  [110 113 118]]

 [[ 53  53  53]
  [ 56  56  56]
  [ 55  55  55]
  ...
  [116 119 124]
  [115 118 123]
  [115 118 123]]

 [[ 56  56  56]
  [ 58  58  58]
  [ 55  55  55]
  ...
  [121 124 129]
  [121 124 129]
  [122 125 130]]]
./data/public/PlantVillage\Tomato_Late_blight\65576adf-cef4-4f1a-8b7c-881e8729bdbf___GHLB2 Leaf 147.JPG
???
[[[ 76 146 139]
  [ 80 150 143]
  [ 83 151 144]
  ...
  [ 13  71  66]
  [ 15  73  68]
  [ 18  76  71]]

 [[ 75 145 138]
  [ 78 148 141]
  [ 83 151 144]
  ...
  [ 21  79  74]
  [ 16  74  69]
  [  9  67  62]]

 [[ 82 152 145]
  [ 81 151 144]
  [ 80 150 143]
  

3it [00:01,  2.16it/s, Epoch=1, Loss=3.393680, Mean Loss=3.551410, Mean F-1=0.015873]

???
[[[122 118 130]
  [118 114 126]
  [114 110 122]
  ...
  [ 88  84  95]
  [ 87  83  94]
  [ 82  78  89]]

 [[109 105 117]
  [111 107 119]
  [114 110 122]
  ...
  [ 88  84  95]
  [ 86  82  93]
  [ 82  78  89]]

 [[ 97  93 105]
  [105 101 113]
  [114 110 122]
  ...
  [ 93  89 100]
  [ 95  91 102]
  [ 95  91 102]]

 ...

 [[155 148 155]
  [149 142 149]
  [146 139 146]
  ...
  [146 142 153]
  [156 152 163]
  [163 159 170]]

 [[157 150 157]
  [152 145 152]
  [151 144 151]
  ...
  [152 148 159]
  [158 154 165]
  [159 155 166]]

 [[156 149 156]
  [152 145 152]
  [152 145 152]
  ...
  [154 150 161]
  [154 150 161]
  [150 146 157]]]
./data/public/PlantVillage\Tomato__Tomato_YellowLeaf__Curl_Virus\1eac2879-1201-4d11-8652-547787cff379___YLCV_GCREC 5357.JPG
???
[[[175 170 172]
  [182 177 179]
  [183 178 180]
  ...
  [160 159 163]
  [154 153 157]
  [158 157 161]]

 [[169 164 166]
  [176 171 173]
  [179 174 176]
  ...
  [154 153 157]
  [151 150 154]
  [156 155 159]]

 [[163 158 160]
  [168 163 165

4it [00:01,  2.88it/s, Epoch=1, Loss=3.385048, Mean Loss=3.509820, Mean F-1=0.032738]

???
[[[117 123 146]
  [127 133 156]
  [ 95 101 124]
  ...
  [114 119 140]
  [134 139 160]
  [137 142 163]]

 [[122 128 151]
  [117 123 146]
  [127 133 156]
  ...
  [132 137 158]
  [123 128 149]
  [102 107 128]]

 [[122 128 151]
  [116 122 145]
  [128 134 157]
  ...
  [133 138 159]
  [126 131 152]
  [176 181 202]]

 ...

 [[118 124 147]
  [126 132 155]
  [112 118 141]
  ...
  [124 129 150]
  [130 135 156]
  [118 123 144]]

 [[114 120 143]
  [120 126 149]
  [115 121 144]
  ...
  [139 144 165]
  [131 136 157]
  [127 132 153]]

 [[110 116 139]
  [106 112 135]
  [129 135 158]
  ...
  [132 137 158]
  [111 116 137]
  [130 135 156]]]
./data/public/PlantVillage\Tomato_Spider_mites_Two_spotted_spider_mite\0e05cc2b-1209-4a5a-9ae1-26b3dd13204b___Com.G_SpM_FL 8428.JPG
???
[[[ 37  27  27]
  [ 37  27  27]
  [ 37  27  27]
  ...
  [166 163 178]
  [169 166 181]
  [166 163 178]]

 [[ 38  28  28]
  [ 37  27  27]
  [ 37  27  27]
  ...
  [155 152 167]
  [155 152 167]
  [155 152 167]]

 [[ 38  28  28]
  [ 38

5it [00:02,  3.39it/s, Epoch=1, Loss=3.204162, Mean Loss=3.448688, Mean F-1=0.045584]

???
[[[ 99 110 140]
  [ 77  88 118]
  [ 83  94 124]
  ...
  [ 85  98 124]
  [ 71  84 110]
  [ 92 105 131]]

 [[ 72  83 113]
  [ 85  96 126]
  [ 79  90 120]
  ...
  [111 124 150]
  [ 81  94 120]
  [ 79  92 118]]

 [[ 92 103 133]
  [109 120 150]
  [ 71  82 112]
  ...
  [108 121 147]
  [ 86  99 125]
  [ 82  95 121]]

 ...

 [[152 160 173]
  [154 162 175]
  [155 163 176]
  ...
  [166 175 188]
  [162 171 184]
  [166 175 188]]

 [[146 154 167]
  [154 162 175]
  [160 168 181]
  ...
  [176 185 198]
  [178 187 200]
  [182 191 204]]

 [[143 151 164]
  [157 165 178]
  [166 174 187]
  ...
  [162 171 184]
  [172 181 194]
  [175 184 197]]]
./data/public/PlantVillage\Pepper__bell___Bacterial_spot\032aa7c4-0a95-4f09-b0bb-1242f4f32d82___NREC_B.Spot 1889.JPG
???
[[[102 100 112]
  [ 98  96 108]
  [ 96  94 106]
  ...
  [ 95  91 103]
  [ 98  94 106]
  [ 79  75  87]]

 [[ 92  90 102]
  [ 87  85  97]
  [ 87  85  97]
  ...
  [ 92  88 100]
  [101  97 109]
  [100  96 108]]

 [[ 90  88 100]
  [ 99  97 109]
  [10

6it [00:02,  3.92it/s, Epoch=1, Loss=3.142368, Mean Loss=3.397635, Mean F-1=0.050108]

???
[[[140 138 150]
  [142 140 152]
  [144 142 154]
  ...
  [114 114 128]
  [130 130 144]
  [113 113 127]]

 [[137 135 147]
  [143 141 153]
  [147 145 157]
  ...
  [111 111 125]
  [124 124 138]
  [110 110 124]]

 [[139 137 149]
  [151 149 161]
  [156 154 166]
  ...
  [115 115 129]
  [124 124 138]
  [113 113 127]]

 ...

 [[169 169 181]
  [149 149 161]
  [160 160 172]
  ...
  [117 120 134]
  [117 120 134]
  [102 105 119]]

 [[141 141 153]
  [139 139 151]
  [157 157 169]
  ...
  [108 111 125]
  [106 109 123]
  [117 120 134]]

 [[144 144 156]
  [155 155 167]
  [162 162 174]
  ...
  [125 128 142]
  [100 103 117]
  [104 107 121]]]
./data/public/PlantVillage\Tomato_Bacterial_spot\2c292d57-d2c0-4147-a551-618f1368f72e___GCREC_Bact.Sp 5903.JPG
???
[[[  4  16  16]
  [ 11  23  23]
  [  0  12  11]
  ...
  [209 191 192]
  [206 188 189]
  [200 182 183]]

 [[  0   2   2]
  [  3  15  15]
  [  0  11  11]
  ...
  [204 186 187]
  [205 187 188]
  [205 187 188]]

 [[  6  16  16]
  [ 15  25  25]
  [ 14  24 

7it [00:02,  4.32it/s, Epoch=1, Loss=3.033253, Mean Loss=3.345580, Mean F-1=0.054741]

???
[[[174 176 177]
  [174 176 177]
  [172 174 175]
  ...
  [153 152 154]
  [155 154 156]
  [155 154 156]]

 [[168 170 171]
  [168 170 171]
  [168 170 171]
  ...
  [150 149 151]
  [152 151 153]
  [153 152 154]]

 [[165 167 168]
  [166 168 169]
  [166 168 169]
  ...
  [153 152 154]
  [155 154 156]
  [156 155 157]]

 ...

 [[119 122 127]
  [118 121 126]
  [113 116 121]
  ...
  [114 117 121]
  [113 116 120]
  [107 110 114]]

 [[115 118 123]
  [114 117 122]
  [119 122 127]
  ...
  [110 113 117]
  [106 109 113]
  [105 108 112]]

 [[114 117 122]
  [110 113 118]
  [118 121 126]
  ...
  [110 113 117]
  [109 112 116]
  [113 116 120]]]
./data/public/PlantVillage\Tomato_Bacterial_spot\0b233197-cd35-4031-80c2-610e7e3a046b___GCREC_Bact.Sp 6095.JPG
???
[[[  3 162 152]
  [  0 149 139]
  [  0 132 120]
  ...
  [ 10 108 108]
  [ 11 104 105]
  [ 10 103 104]]

 [[  5 166 156]
  [  2 156 145]
  [  0 139 126]
  ...
  [  2  95  96]
  [  1  93  94]
  [  0  92  93]]

 [[  8 172 161]
  [  5 163 151]
  [  3 147 

8it [00:02,  4.71it/s, Epoch=1, Loss=2.578950, Mean Loss=3.249751, Mean F-1=0.066225]

???
[[[132 132 138]
  [ 74  74  80]
  [108 108 114]
  ...
  [113 114 124]
  [138 139 149]
  [ 82  83  93]]

 [[110 110 116]
  [134 134 140]
  [129 129 135]
  ...
  [112 113 123]
  [118 119 129]
  [123 124 134]]

 [[139 139 145]
  [121 121 127]
  [129 129 135]
  ...
  [107 108 118]
  [116 117 127]
  [106 107 117]]

 ...

 [[188 188 194]
  [146 146 152]
  [170 170 176]
  ...
  [157 158 168]
  [150 151 161]
  [142 143 153]]

 [[150 150 156]
  [138 138 144]
  [156 156 162]
  ...
  [150 151 161]
  [170 171 181]
  [160 161 171]]

 [[145 145 151]
  [166 166 172]
  [152 152 158]
  ...
  [150 151 161]
  [181 182 192]
  [145 146 156]]]
./data/public/PlantVillage\Tomato__Tomato_YellowLeaf__Curl_Virus\4216d51d-afb3-4b53-9d16-45d29d8c708a___YLCV_GCREC 2171.JPG
???
[[[137 134 149]
  [138 135 150]
  [138 135 150]
  ...
  [143 140 156]
  [153 150 166]
  [136 133 149]]

 [[162 159 174]
  [147 144 159]
  [148 145 160]
  ...
  [133 130 146]
  [140 137 153]
  [146 143 159]]

 [[153 150 165]
  [136 133 148

9it [00:02,  4.88it/s, Epoch=1, Loss=2.979944, Mean Loss=3.219773, Mean F-1=0.070314]

???
[[[157 147 160]
  [155 145 158]
  [151 141 154]
  ...
  [194 186 193]
  [194 186 193]
  [192 184 191]]

 [[152 142 155]
  [150 140 153]
  [147 137 150]
  ...
  [191 183 190]
  [190 182 189]
  [188 180 187]]

 [[149 139 152]
  [147 137 150]
  [146 136 149]
  ...
  [192 184 191]
  [190 182 189]
  [187 179 186]]

 ...

 [[117 108 128]
  [124 115 135]
  [118 109 129]
  ...
  [139 129 145]
  [128 118 134]
  [130 120 136]]

 [[135 126 146]
  [116 107 127]
  [125 116 136]
  ...
  [139 129 145]
  [163 153 169]
  [132 122 138]]

 [[117 108 128]
  [139 130 150]
  [131 122 142]
  ...
  [135 125 141]
  [138 128 144]
  [148 138 154]]]
./data/public/PlantVillage\Tomato__Target_Spot\2cfdcad0-ed4d-496a-80dc-38852264f4cc___Com.G_TgS_FL 0893.JPG
???
[[[156 139 143]
  [124 107 111]
  [109  92  96]
  ...
  [131 113 120]
  [137 119 126]
  [111  93 100]]

 [[140 123 127]
  [117 100 104]
  [140 123 127]
  ...
  [ 91  73  80]
  [113  95 102]
  [ 99  81  88]]

 [[115  98 102]
  [115  98 102]
  [121 104 108

10it [00:03,  5.18it/s, Epoch=1, Loss=2.516117, Mean Loss=3.149407, Mean F-1=0.068838]

???
[[[122 118 130]
  [112 108 120]
  [133 129 141]
  ...
  [165 161 167]
  [171 167 173]
  [183 179 185]]

 [[129 125 137]
  [107 103 115]
  [122 118 130]
  ...
  [182 178 184]
  [171 167 173]
  [169 165 171]]

 [[123 119 131]
  [102  98 110]
  [124 120 132]
  ...
  [176 172 178]
  [164 160 166]
  [166 162 168]]

 ...

 [[116 110 121]
  [123 117 128]
  [121 115 126]
  ...
  [158 152 163]
  [160 154 165]
  [163 157 168]]

 [[120 114 125]
  [127 121 132]
  [124 118 129]
  ...
  [144 138 149]
  [147 141 152]
  [149 143 154]]

 [[102  96 107]
  [120 114 125]
  [126 120 131]
  ...
  [154 148 159]
  [156 150 161]
  [158 152 163]]]
./data/public/PlantVillage\Tomato_Spider_mites_Two_spotted_spider_mite\d58b9f9a-d62c-44c4-8a76-dba4ccc7fca8___Com.G_SpM_FL 9562.JPG
???
[[[130 132 143]
  [126 128 139]
  [130 132 143]
  ...
  [121 120 130]
  [110 109 119]
  [154 153 163]]

 [[121 123 134]
  [114 116 127]
  [118 120 131]
  ...
  [110 109 119]
  [ 88  87  97]
  [114 113 123]]

 [[131 133 144]
  [119

11it [00:03,  5.27it/s, Epoch=1, Loss=2.499409, Mean Loss=3.090317, Mean F-1=0.075499]

???
[[[161 128 113]
  [158 125 110]
  [156 123 108]
  ...
  [152 117 103]
  [149 114 100]
  [148 113  99]]

 [[161 128 113]
  [159 126 111]
  [157 124 109]
  ...
  [153 118 104]
  [152 117 103]
  [151 116 102]]

 [[162 129 114]
  [159 126 111]
  [157 124 109]
  ...
  [154 119 105]
  [154 119 105]
  [154 119 105]]

 ...

 [[ 98  67  64]
  [ 99  68  65]
  [ 99  68  65]
  ...
  [113  84  77]
  [113  84  77]
  [113  84  77]]

 [[ 99  68  65]
  [ 99  68  65]
  [100  69  66]
  ...
  [113  84  77]
  [113  84  77]
  [113  84  77]]

 [[100  69  66]
  [101  70  67]
  [101  70  67]
  ...
  [113  84  77]
  [113  84  77]
  [113  84  77]]]
./data/public/PlantVillage\Tomato_Leaf_Mold\aac3fb74-6413-4f4b-ba38-82fe0f2f135d___Crnl_L.Mold 8942.JPG
???
[[[122 106 113]
  [119 103 110]
  [144 128 135]
  ...
  [ 93  76  85]
  [111  94 103]
  [117 100 109]]

 [[115  99 106]
  [119 103 110]
  [140 124 131]
  ...
  [100  83  92]
  [120 103 112]
  [ 89  72  81]]

 [[120 104 111]
  [125 109 116]
  [131 115 122]
  

12it [00:03,  5.48it/s, Epoch=1, Loss=3.180142, Mean Loss=3.097802, Mean F-1=0.070530]

???
[[[166 162 173]
  [186 182 193]
  [192 188 199]
  ...
  [190 200 210]
  [198 208 218]
  [157 170 178]]

 [[230 226 237]
  [183 179 190]
  [157 153 164]
  ...
  [147 156 166]
  [176 185 194]
  [144 155 163]]

 [[203 199 210]
  [171 167 178]
  [171 167 178]
  ...
  [178 183 192]
  [148 153 162]
  [187 193 200]]

 ...

 [[180 174 185]
  [178 172 183]
  [176 170 181]
  ...
  [178 174 186]
  [178 174 186]
  [174 170 182]]

 [[185 179 190]
  [182 176 187]
  [179 173 184]
  ...
  [178 174 186]
  [179 175 187]
  [177 173 185]]

 [[184 178 189]
  [182 176 187]
  [180 174 185]
  ...
  [179 175 187]
  [181 177 189]
  [179 175 187]]]
./data/public/PlantVillage\Pepper__bell___Bacterial_spot\517e3352-9e28-4b42-970b-2aa198203960___JR_B.Spot 8855.JPG
???
[[[  0   2   1]
  [  0   1   1]
  [ 10   8   8]
  ...
  [230 112 130]
  [232 119 133]
  [238 127 141]]

 [[  0   4   6]
  [  0   4   5]
  [  7   0   1]
  ...
  [236 111 127]
  [237 115 131]
  [242 124 137]]

 [[  0   3   7]
  [  7   3   9]
  [ 22 

13it [00:03,  5.63it/s, Epoch=1, Loss=2.617509, Mean Loss=3.033679, Mean F-1=0.070900]

???
[[[ 93  93  93]
  [ 93  93  93]
  [ 93  93  93]
  ...
  [117 115 114]
  [122 120 119]
  [126 124 123]]

 [[ 90  90  90]
  [ 90  90  90]
  [ 92  92  92]
  ...
  [121 119 118]
  [123 121 120]
  [125 123 122]]

 [[ 88  88  88]
  [ 88  88  88]
  [ 90  90  90]
  ...
  [127 125 124]
  [127 125 124]
  [128 126 125]]

 ...

 [[115 120 121]
  [115 120 121]
  [115 120 121]
  ...
  [123 128 127]
  [125 130 129]
  [127 132 131]]

 [[114 119 120]
  [114 119 120]
  [113 118 119]
  ...
  [122 127 126]
  [124 129 128]
  [125 130 129]]

 [[113 118 119]
  [113 118 119]
  [112 117 118]
  ...
  [122 127 126]
  [123 128 127]
  [124 129 128]]]
./data/public/PlantVillage\Tomato__Tomato_YellowLeaf__Curl_Virus\7ac74262-4823-4304-9ba6-9741477e168c___UF.GRC_YLCV_Lab 02669.JPG
???
[[[205 186 189]
  [195 176 179]
  [196 177 180]
  ...
  [159 140 149]
  [161 141 153]
  [145 125 137]]

 [[191 172 175]
  [170 151 154]
  [161 142 145]
  ...
  [156 137 146]
  [154 134 146]
  [140 120 132]]

 [[181 162 165]
  [173 1

15it [00:03,  5.55it/s, Epoch=1, Loss=2.911536, Mean Loss=3.025536, Mean F-1=0.066906]

???
[[[203 189 195]
  [198 184 190]
  [215 201 205]
  ...
  [199 185 186]
  [230 216 217]
  [199 185 186]]

 [[215 201 207]
  [198 184 190]
  [197 183 187]
  ...
  [207 193 194]
  [212 198 199]
  [207 193 194]]

 [[206 192 198]
  [194 180 186]
  [195 181 185]
  ...
  [205 191 192]
  [191 177 178]
  [210 196 197]]

 ...

 [[147 131 138]
  [149 133 140]
  [146 130 137]
  ...
  [155 141 143]
  [160 146 148]
  [164 150 152]]

 [[138 121 130]
  [143 126 135]
  [143 126 135]
  ...
  [141 127 129]
  [143 129 131]
  [150 136 138]]

 [[131 114 123]
  [141 124 133]
  [147 130 139]
  ...
  [149 135 137]
  [149 135 137]
  [157 143 145]]]
./data/public/PlantVillage\Potato___Early_blight\1daae61a-7014-4efe-b855-018999a5be9b___RS_Early.B 6852.JPG
???
[[[158 155 171]
  [145 142 158]
  [158 155 171]
  ...
  [176 177 187]
  [162 163 173]
  [180 181 191]]

 [[162 159 175]
  [158 155 171]
  [173 170 186]
  ...
  [161 162 172]
  [174 175 185]
  [166 167 177]]

 [[159 156 172]
  [158 155 171]
  [170 167 183

16it [00:04,  5.62it/s, Epoch=1, Loss=2.759454, Mean Loss=3.008906, Mean F-1=0.070408]

???
[[[148 131 144]
  [146 129 142]
  [146 129 142]
  ...
  [136 116 129]
  [157 137 150]
  [151 131 144]]

 [[134 117 130]
  [138 121 134]
  [140 123 136]
  ...
  [130 110 123]
  [143 123 136]
  [134 114 127]]

 [[130 113 126]
  [137 120 133]
  [138 121 134]
  ...
  [137 117 130]
  [144 124 137]
  [135 115 128]]

 ...

 [[107  91 108]
  [101  85 102]
  [ 98  82  99]
  ...
  [110  94 111]
  [109  93 110]
  [109  93 110]]

 [[100  84 101]
  [ 99  83 100]
  [101  85 102]
  ...
  [111  95 112]
  [119 103 120]
  [118 102 119]]

 [[106  90 107]
  [102  86 103]
  [ 95  79  96]
  ...
  [107  91 108]
  [120 104 121]
  [119 103 120]]]
./data/public/PlantVillage\Tomato_Septoria_leaf_spot\bce32f04-c236-45ed-b636-c92721eb5892___Keller.St_CG 1934.JPG
???
[[[190 202 214]
  [189 201 213]
  [184 196 208]
  ...
  [154 164 181]
  [144 154 171]
  [160 170 187]]

 [[186 198 210]
  [184 196 208]
  [181 193 205]
  ...
  [148 158 175]
  [139 149 166]
  [145 155 172]]

 [[178 190 202]
  [175 187 199]
  [172 1

17it [00:04,  5.74it/s, Epoch=1, Loss=2.423832, Mean Loss=2.974490, Mean F-1=0.083260]

???
[[[159 149 161]
  [167 157 169]
  [144 134 146]
  ...
  [103  96 111]
  [ 94  87 102]
  [124 117 132]]

 [[147 137 149]
  [157 147 159]
  [147 137 149]
  ...
  [109 102 117]
  [146 139 154]
  [131 124 139]]

 [[151 141 153]
  [161 151 163]
  [161 151 163]
  ...
  [105  98 113]
  [131 124 139]
  [ 75  68  83]]

 ...

 [[161 154 167]
  [157 150 163]
  [153 146 159]
  ...
  [124 119 134]
  [ 81  76  91]
  [116 111 126]]

 [[163 156 169]
  [158 151 164]
  [153 146 159]
  ...
  [113 108 123]
  [ 76  71  86]
  [126 121 136]]

 [[150 143 156]
  [149 142 155]
  [149 142 155]
  ...
  [138 133 148]
  [120 115 130]
  [104  99 114]]]
./data/public/PlantVillage\Tomato__Target_Spot\0f5f2efc-3544-4fbc-8dcc-e623577596bc___Com.G_TgS_FL 9869.JPG
???
[[[117 113 124]
  [121 117 128]
  [ 75  71  82]
  ...
  [187 185 191]
  [180 178 184]
  [187 185 191]]

 [[158 154 165]
  [104 100 111]
  [110 106 117]
  ...
  [182 180 186]
  [172 170 176]
  [170 168 174]]

 [[125 121 132]
  [134 130 141]
  [128 124 135

18it [00:04,  5.68it/s, Epoch=1, Loss=2.387641, Mean Loss=2.941887, Mean F-1=0.085674]

???
[[[ 90  87 103]
  [ 81  78  94]
  [ 66  63  79]
  ...
  [144 141 156]
  [139 136 151]
  [130 127 142]]

 [[ 89  86 102]
  [ 91  88 104]
  [ 80  77  93]
  ...
  [139 136 151]
  [142 139 154]
  [137 134 149]]

 [[ 82  79  95]
  [ 95  92 108]
  [ 92  89 105]
  ...
  [139 136 151]
  [143 140 155]
  [140 137 152]]

 ...

 [[138 134 146]
  [136 132 144]
  [125 121 133]
  ...
  [149 142 155]
  [150 143 156]
  [153 146 159]]

 [[122 118 130]
  [116 112 124]
  [125 121 133]
  ...
  [156 149 162]
  [155 148 161]
  [157 150 163]]

 [[126 122 134]
  [115 111 123]
  [108 104 116]
  ...
  [149 142 155]
  [144 137 150]
  [143 136 149]]]
./data/public/PlantVillage\Tomato_Bacterial_spot\80c97a5c-e7db-4f3c-8de0-0fecb6c451f1___GCREC_Bact.Sp 3553.JPG
???
[[[145 144 154]
  [130 129 139]
  [154 153 163]
  ...
  [139 140 150]
  [139 140 150]
  [141 142 152]]

 [[155 154 164]
  [159 158 168]
  [125 124 134]
  ...
  [132 133 143]
  [129 130 140]
  [130 131 141]]

 [[138 137 147]
  [129 128 138]
  [145 144 

19it [00:04,  5.55it/s, Epoch=1, Loss=2.471349, Mean Loss=2.917122, Mean F-1=0.084173]

???
[[[171 165 170]
  [169 163 168]
  [168 162 167]
  ...
  [154 148 153]
  [156 150 155]
  [158 152 157]]

 [[163 157 162]
  [163 157 162]
  [165 159 164]
  ...
  [157 151 156]
  [159 153 158]
  [161 155 160]]

 [[162 156 161]
  [163 157 162]
  [165 159 164]
  ...
  [155 149 154]
  [157 151 156]
  [156 150 155]]

 ...

 [[ 89  88  98]
  [ 87  86  96]
  [ 87  86  96]
  ...
  [ 78  78  90]
  [ 74  74  86]
  [ 70  70  82]]

 [[ 91  90 100]
  [ 88  87  97]
  [ 87  86  96]
  ...
  [ 73  73  85]
  [ 70  70  82]
  [ 67  67  79]]

 [[ 92  91 101]
  [ 89  88  98]
  [ 88  87  97]
  ...
  [ 83  83  95]
  [ 85  85  97]
  [ 86  86  98]]]
./data/public/PlantVillage\Tomato_Late_blight\f879b7d4-efe4-4b31-8a89-35db50d561c9___RS_Late.B 4897.JPG
???
[[[ 48  96  44]
  [ 51 100  46]
  [ 57 104  48]
  ...
  [ 62  71  51]
  [ 94 104  92]
  [128 139 129]]

 [[ 52 100  48]
  [ 53 102  48]
  [ 57 104  48]
  ...
  [ 68  77  57]
  [108 118 105]
  [144 158 146]]

 [[ 58 106  54]
  [ 56 105  51]
  [ 56 103  47]
  

20it [00:04,  5.56it/s, Epoch=1, Loss=2.408613, Mean Loss=2.891697, Mean F-1=0.095873]

???
[[[170 159 162]
  [173 162 165]
  [172 161 164]
  ...
  [139 125 129]
  [149 135 139]
  [153 139 143]]

 [[176 165 168]
  [177 166 169]
  [175 164 167]
  ...
  [156 142 146]
  [148 134 138]
  [159 145 149]]

 [[182 171 174]
  [181 170 173]
  [177 166 169]
  ...
  [148 134 138]
  [149 135 139]
  [146 132 136]]

 ...

 [[163 156 163]
  [167 160 167]
  [168 161 168]
  ...
  [164 160 166]
  [165 161 167]
  [169 165 171]]

 [[200 193 200]
  [203 196 203]
  [220 213 220]
  ...
  [167 163 169]
  [170 166 172]
  [173 169 175]]

 [[171 164 171]
  [188 181 188]
  [195 188 195]
  ...
  [164 160 166]
  [158 154 160]
  [152 148 154]]]
./data/public/PlantVillage\Pepper__bell___healthy\265d5430-3017-440a-b4f3-abfa0d2cbaed___JR_HL 7608.JPG
???
[[[116 106 122]
  [130 120 136]
  [154 144 160]
  ...
  [135 126 146]
  [121 112 132]
  [122 113 133]]

 [[151 141 157]
  [148 138 154]
  [146 136 152]
  ...
  [127 118 138]
  [119 110 130]
  [114 105 125]]

 [[161 151 167]
  [130 120 136]
  [135 125 141]
  

21it [00:05,  5.43it/s, Epoch=1, Loss=2.466763, Mean Loss=2.871462, Mean F-1=0.104324]

[[[135 124 144]
  [135 124 144]
  [136 125 145]
  ...
  [119 107 125]
  [119 107 125]
  [112 100 118]]

 [[133 122 142]
  [134 123 143]
  [136 125 145]
  ...
  [118 106 124]
  [120 108 126]
  [117 105 123]]

 [[133 122 142]
  [135 124 144]
  [137 126 146]
  ...
  [113 101 119]
  [115 103 121]
  [116 104 122]]

 ...

 [[ 98  86 108]
  [ 95  83 105]
  [ 95  83 105]
  ...
  [ 79  69  86]
  [ 85  75  92]
  [ 89  79  96]]

 [[108  96 118]
  [100  88 110]
  [ 95  83 105]
  ...
  [ 83  73  90]
  [ 87  77  94]
  [ 90  80  97]]

 [[108  96 118]
  [ 97  85 107]
  [ 88  76  98]
  ...
  [ 85  75  92]
  [ 87  77  94]
  [ 88  78  95]]]
./data/public/PlantVillage\Tomato__Tomato_mosaic_virus\f90809d6-8b8d-4a7d-81df-c0d708ed9bb4___PSU_CG 2176.JPG
???
[[[114 116 117]
  [111 113 114]
  [110 112 113]
  ...
  [135 135 135]
  [136 136 136]
  [137 137 137]]

 [[111 113 114]
  [109 111 112]
  [107 109 110]
  ...
  [135 135 135]
  [136 136 136]
  [136 136 136]]

 [[110 112 113]
  [113 115 116]
  [114 116 117]


22it [00:05,  5.29it/s, Epoch=1, Loss=2.155765, Mean Loss=2.838930, Mean F-1=0.108736]

???
[[[157 141 148]
  [136 120 127]
  [153 137 144]
  ...
  [127 111 118]
  [133 117 124]
  [125 109 116]]

 [[147 131 138]
  [135 119 126]
  [151 135 142]
  ...
  [128 112 119]
  [133 117 124]
  [126 110 117]]

 [[142 126 133]
  [141 125 132]
  [151 135 142]
  ...
  [127 111 118]
  [132 116 123]
  [126 110 117]]

 ...

 [[204 191 193]
  [209 196 198]
  [212 199 201]
  ...
  [195 178 181]
  [197 180 183]
  [197 180 183]]

 [[208 195 197]
  [214 201 203]
  [218 205 207]
  ...
  [192 175 178]
  [188 171 174]
  [185 168 171]]

 [[203 190 192]
  [210 197 199]
  [215 202 204]
  ...
  [197 180 183]
  [193 176 179]
  [190 173 176]]]
./data/public/PlantVillage\Tomato__Target_Spot\37a012b0-0bf4-4e52-a933-2e422f54fd3e___Com.G_TgS_FL 0669.JPG
???
[[[147 138 141]
  [130 121 124]
  [125 116 119]
  ...
  [123 105 104]
  [128 110 109]
  [132 114 113]]

 [[156 147 150]
  [157 148 151]
  [154 145 148]
  ...
  [123 105 104]
  [125 107 106]
  [129 111 110]]

 [[152 143 146]
  [148 139 142]
  [139 130 133

23it [00:05,  5.43it/s, Epoch=1, Loss=1.816892, Mean Loss=2.794494, Mean F-1=0.122819]

???
[[[175 156 165]
  [180 161 170]
  [169 150 159]
  ...
  [135 116 125]
  [152 133 142]
  [161 142 151]]

 [[148 129 138]
  [169 150 159]
  [205 186 195]
  ...
  [132 113 122]
  [149 130 139]
  [148 129 138]]

 [[203 184 193]
  [202 183 192]
  [172 153 162]
  ...
  [133 114 123]
  [138 119 128]
  [122 103 112]]

 ...

 [[132 111 126]
  [135 114 129]
  [147 126 141]
  ...
  [ 98  80  97]
  [101  83 100]
  [104  86 103]]

 [[143 122 137]
  [126 105 120]
  [131 110 125]
  ...
  [ 94  76  93]
  [ 97  79  96]
  [ 85  67  84]]

 [[113  92 107]
  [128 107 122]
  [140 119 134]
  ...
  [120 102 119]
  [125 107 124]
  [ 97  79  96]]]
./data/public/PlantVillage\Tomato__Tomato_mosaic_virus\29bbbfcc-76ef-4506-9c1b-1a749646856e___PSU_CG 2184.JPG
???
[[[137 114 119]
  [134 111 116]
  [142 119 124]
  ...
  [117  94 102]
  [116  93 101]
  [120  97 105]]

 [[122  99 104]
  [138 115 120]
  [135 112 117]
  ...
  [122  99 107]
  [121  98 106]
  [124 101 109]]

 [[144 121 126]
  [163 140 145]
  [134 111 1

24it [00:05,  5.43it/s, Epoch=1, Loss=2.309239, Mean Loss=2.774275, Mean F-1=0.126392]

???
[[[225 255 255]
  [225 255 255]
  [225 254 255]
  ...
  [234 206 226]
  [242 215 231]
  [245 219 233]]

 [[189 251 255]
  [166 233 236]
  [161 233 233]
  ...
  [234 207 227]
  [242 216 232]
  [245 220 234]]

 [[141 255 255]
  [111 249 242]
  [ 82 240 228]
  ...
  [230 204 227]
  [242 218 236]
  [247 224 239]]

 ...

 [[192 178 180]
  [206 191 195]
  [221 201 214]
  ...
  [214 172 207]
  [213 164 202]
  [224 173 211]]

 [[195 179 180]
  [208 191 194]
  [222 200 212]
  ...
  [223 179 215]
  [219 168 206]
  [226 171 210]]

 [[192 177 175]
  [205 188 191]
  [221 200 209]
  ...
  [228 184 220]
  [223 170 209]
  [226 169 208]]]
./data/public/PlantDoc/train/Late-blight_jpg.rf.a58860415f3fb8e40b300f4e5bc8cd86.jpg
???
[[[126  93  84]
  [133 100  91]
  [131  98  89]
  ...
  [187 152 139]
  [184 149 136]
  [182 147 134]]

 [[124  91  82]
  [133 100  91]
  [133 100  91]
  ...
  [188 153 140]
  [185 150 137]
  [183 148 135]]

 [[123  90  81]
  [131  98  89]
  [134 101  92]
  ...
  [187 152 139]

25it [00:05,  5.37it/s, Epoch=1, Loss=2.381724, Mean Loss=2.758573, Mean F-1=0.125337]

???
[[[133 127 128]
  [133 127 128]
  [134 128 129]
  ...
  [180 170 170]
  [180 170 170]
  [179 169 169]]

 [[129 123 124]
  [134 128 129]
  [139 133 134]
  ...
  [183 173 173]
  [183 173 173]
  [184 174 174]]

 [[145 139 140]
  [144 138 139]
  [144 138 139]
  ...
  [180 170 170]
  [181 171 171]
  [182 172 172]]

 ...

 [[ 95  90  92]
  [107 102 104]
  [107 102 104]
  ...
  [149 143 144]
  [150 144 145]
  [151 145 146]]

 [[109 104 106]
  [111 106 108]
  [109 104 106]
  ...
  [147 141 142]
  [148 142 143]
  [149 143 144]]

 [[118 113 115]
  [116 111 113]
  [121 116 118]
  ...
  [145 139 140]
  [146 140 141]
  [147 141 142]]]
./data/public/PlantVillage\Tomato_Early_blight\76b0d46d-8e2b-463b-8cba-eaeee6dc1851___RS_Erly.B 9527.JPG
???
[[[173 166 173]
  [162 155 162]
  [139 132 139]
  ...
  [ 99  93 104]
  [104  98 109]
  [ 96  90 101]]

 [[157 150 157]
  [176 169 176]
  [122 115 122]
  ...
  [118 112 123]
  [107 101 112]
  [ 95  89 100]]

 [[153 146 153]
  [162 155 162]
  [138 131 138]
 

26it [00:05,  5.38it/s, Epoch=1, Loss=2.721624, Mean Loss=2.757152, Mean F-1=0.128406]

???
[[[ 24  24  24]
  [ 24  24  24]
  [ 24  24  24]
  ...
  [ 33 141 129]
  [ 42 147 136]
  [ 62 167 156]]

 [[ 24  24  24]
  [ 24  24  24]
  [ 24  24  24]
  ...
  [ 49 157 145]
  [ 58 163 152]
  [ 76 181 170]]

 [[ 24  24  24]
  [ 24  24  24]
  [ 24  24  24]
  ...
  [ 66 176 164]
  [ 75 183 171]
  [ 88 196 184]]

 ...

 [[ 40 165 173]
  [ 44 171 179]
  [ 48 180 187]
  ...
  [ 22  27  26]
  [ 21  27  26]
  [ 20  26  25]]

 [[ 60 184 192]
  [ 56 181 189]
  [ 48 178 185]
  ...
  [ 22  27  26]
  [ 21  27  26]
  [ 20  26  25]]

 [[ 72 196 204]
  [ 62 187 195]
  [ 47 177 184]
  ...
  [ 22  27  26]
  [ 21  27  26]
  [ 20  26  25]]]
./data/public/PlantDoc/train/ebleafb_jpg.rf.732497a954ed2f4ba336b4d32b3370d6.jpg
???
[[[197 185 191]
  [185 173 179]
  [200 188 194]
  ...
  [114 100 112]
  [141 127 139]
  [137 123 135]]

 [[212 200 206]
  [203 191 197]
  [204 192 198]
  ...
  [125 111 123]
  [128 114 126]
  [119 105 117]]

 [[188 176 182]
  [191 179 185]
  [191 179 185]
  ...
  [111  97 109]
  [

27it [00:06,  5.47it/s, Epoch=1, Loss=2.080657, Mean Loss=2.732096, Mean F-1=0.136797]

???
[[[130 126 131]
  [111 107 112]
  [134 130 135]
  ...
  [147 143 148]
  [107 103 108]
  [144 140 145]]

 [[130 126 131]
  [107 103 108]
  [119 115 120]
  ...
  [107 103 108]
  [129 125 130]
  [148 144 149]]

 [[119 115 120]
  [112 108 113]
  [119 115 120]
  ...
  [166 162 167]
  [147 143 148]
  [109 105 110]]

 ...

 [[ 85  83  83]
  [ 61  59  59]
  [ 59  57  57]
  ...
  [ 77  73  72]
  [108 104 103]
  [103  99  98]]

 [[ 81  79  79]
  [ 62  60  60]
  [ 84  82  82]
  ...
  [ 73  69  68]
  [ 78  74  73]
  [ 93  89  88]]

 [[ 86  84  84]
  [ 71  69  69]
  [104 102 102]
  ...
  [129 125 124]
  [ 96  92  91]
  [ 92  88  87]]]
./data/public/PlantVillage\Tomato_healthy\2e485f1d-5aa5-4d56-8733-9625ed4d000c___GH_HL Leaf 344.JPG
???
[[[161 163 181]
  [163 165 183]
  [166 168 186]
  ...
  [ 13  12  22]
  [ 28  24  36]
  [ 36  29  44]]

 [[165 167 185]
  [167 169 187]
  [168 170 188]
  ...
  [ 11  10  20]
  [ 25  21  33]
  [ 33  26  41]]

 [[165 167 185]
  [166 168 186]
  [167 169 187]
  ...


28it [00:06,  5.29it/s, Epoch=1, Loss=2.273086, Mean Loss=2.715703, Mean F-1=0.140858]

???
[[[114 114 130]
  [ 97  97 113]
  [101 101 117]
  ...
  [ 89  94 115]
  [ 93  98 119]
  [ 78  83 104]]

 [[135 135 151]
  [126 126 142]
  [127 127 143]
  ...
  [ 74  79 100]
  [ 80  85 106]
  [ 81  86 107]]

 [[124 124 140]
  [126 126 142]
  [131 131 147]
  ...
  [ 80  85 106]
  [ 81  86 107]
  [ 91  96 117]]

 ...

 [[151 151 163]
  [146 146 158]
  [137 137 149]
  ...
  [157 157 169]
  [157 157 169]
  [153 153 165]]

 [[143 143 155]
  [144 144 156]
  [142 142 154]
  ...
  [153 153 165]
  [156 156 168]
  [155 155 167]]

 [[143 143 155]
  [148 148 160]
  [149 149 161]
  ...
  [145 145 157]
  [145 145 157]
  [146 146 158]]]
./data/public/PlantVillage\Tomato__Tomato_YellowLeaf__Curl_Virus\35d0ae49-02c5-402a-9c78-16aebc1821ad___YLCV_NREC 2746.JPG
???
[[[193 192 202]
  [201 200 210]
  [219 218 228]
  ...
  [166 166 182]
  [169 169 185]
  [154 154 170]]

 [[209 208 218]
  [202 201 211]
  [203 202 212]
  ...
  [159 159 175]
  [151 151 167]
  [143 143 159]]

 [[188 187 197]
  [192 191 201]

29it [00:06,  5.41it/s, Epoch=1, Loss=2.225354, Mean Loss=2.698795, Mean F-1=0.142819]

???
[[[129 134 133]
  [127 132 131]
  [125 130 129]
  ...
  [128 133 132]
  [131 136 135]
  [134 139 138]]

 [[127 132 131]
  [126 131 130]
  [124 129 128]
  ...
  [127 132 131]
  [129 134 133]
  [131 136 135]]

 [[126 131 130]
  [125 130 129]
  [125 130 129]
  ...
  [130 135 134]
  [130 135 134]
  [130 135 134]]

 ...

 [[152 157 156]
  [152 157 156]
  [150 155 154]
  ...
  [135 140 139]
  [135 140 139]
  [135 140 139]]

 [[152 157 156]
  [153 158 157]
  [151 156 155]
  ...
  [136 141 140]
  [136 141 140]
  [136 141 140]]

 [[150 155 154]
  [152 157 156]
  [149 154 153]
  ...
  [137 142 141]
  [138 143 142]
  [138 143 142]]]
./data/public/PlantVillage\Tomato__Tomato_YellowLeaf__Curl_Virus\1af87bdf-0bd0-4146-93e5-cc5f97d98b05___UF.GRC_YLCV_Lab 01968.JPG
???
[[[171 180 194]
  [164 173 187]
  [157 166 180]
  ...
  [147 155 172]
  [134 142 159]
  [121 129 146]]

 [[186 195 209]
  [171 180 194]
  [154 163 177]
  ...
  [138 146 163]
  [128 136 153]
  [129 137 154]]

 [[147 156 170]
  [158 1

30it [00:06,  5.29it/s, Epoch=1, Loss=2.266510, Mean Loss=2.684385, Mean F-1=0.144063]

???
[[[196 185 188]
  [200 189 192]
  [202 191 194]
  ...
  [229 212 215]
  [180 163 166]
  [199 182 185]]

 [[247 236 239]
  [217 206 209]
  [240 229 232]
  ...
  [200 183 186]
  [156 139 142]
  [176 159 162]]

 [[192 181 184]
  [215 204 207]
  [198 187 190]
  ...
  [192 175 178]
  [210 193 196]
  [191 174 177]]

 ...

 [[189 177 183]
  [169 157 163]
  [157 145 151]
  ...
  [147 131 138]
  [163 147 154]
  [162 146 153]]

 [[169 157 163]
  [156 144 150]
  [164 152 158]
  ...
  [160 144 151]
  [170 154 161]
  [173 157 164]]

 [[157 145 151]
  [158 146 152]
  [197 185 191]
  ...
  [154 138 145]
  [148 132 139]
  [141 125 132]]]
./data/public/PlantVillage\Tomato_Septoria_leaf_spot\906be65e-a9f5-4ea9-bb47-4706aa2bf180___Matt.S_CG 7526.JPG
???
[[[153 121 126]
  [148 116 121]
  [152 120 125]
  ...
  [173 139 140]
  [176 142 143]
  [174 140 141]]

 [[146 114 119]
  [144 112 117]
  [151 119 124]
  ...
  [209 175 176]
  [157 123 124]
  [171 137 138]]

 [[147 115 120]
  [147 115 120]
  [155 123 

31it [00:06,  5.35it/s, Epoch=1, Loss=2.341527, Mean Loss=2.673325, Mean F-1=0.142104]

???
[[[131 126 127]
  [131 126 127]
  [129 124 125]
  ...
  [116 116 116]
  [107 107 107]
  [105 105 105]]

 [[122 117 118]
  [129 124 125]
  [134 129 130]
  ...
  [107 107 107]
  [100 100 100]
  [106 106 106]]

 [[119 114 115]
  [127 122 123]
  [134 129 130]
  ...
  [ 99  99  99]
  [ 94  94  94]
  [106 106 106]]

 ...

 [[141 132 129]
  [165 156 153]
  [132 123 120]
  ...
  [110 108 107]
  [109 107 106]
  [107 105 104]]

 [[131 122 119]
  [162 153 150]
  [136 127 124]
  ...
  [111 109 108]
  [105 103 102]
  [ 96  94  93]]

 [[129 120 117]
  [151 142 139]
  [131 122 119]
  ...
  [121 119 118]
  [111 109 108]
  [ 96  94  93]]]
./data/public/PlantVillage\Tomato_Early_blight\7b32caa4-0d67-4b84-a1bf-cf9dffd7ffe5___RS_Erly.B 6405.JPG
???
[[[149 150 154]
  [142 143 147]
  [139 140 144]
  ...
  [166 168 169]
  [165 167 168]
  [170 172 173]]

 [[136 137 141]
  [130 131 135]
  [130 131 135]
  ...
  [166 168 169]
  [165 167 168]
  [167 169 170]]

 [[143 144 148]
  [139 140 144]
  [140 141 145]
 

32it [00:07,  5.35it/s, Epoch=1, Loss=2.117164, Mean Loss=2.655945, Mean F-1=0.144069]

???
[[[198 198 210]
  [194 194 206]
  [189 189 201]
  ...
  [178 179 193]
  [177 178 192]
  [177 178 192]]

 [[195 195 207]
  [191 191 203]
  [187 187 199]
  ...
  [178 179 193]
  [178 179 193]
  [177 178 192]]

 [[190 190 202]
  [188 188 200]
  [185 185 197]
  ...
  [180 181 195]
  [178 179 193]
  [177 178 192]]

 ...

 [[174 175 189]
  [139 140 154]
  [124 127 142]
  ...
  [105 107 125]
  [127 129 147]
  [ 99 101 119]]

 [[161 162 176]
  [117 118 132]
  [123 126 141]
  ...
  [147 149 167]
  [119 121 139]
  [151 153 171]]

 [[138 139 153]
  [112 113 127]
  [142 145 160]
  ...
  [132 134 152]
  [145 147 165]
  [123 125 143]]]
./data/public/PlantVillage\Tomato_Late_blight\66f03c1a-6810-41b2-93cb-ccc1630a18d4___RS_Late.B 4882.JPG
???
[[[174 170 175]
  [132 128 133]
  [160 156 161]
  ...
  [116 115 125]
  [ 97  96 106]
  [113 112 122]]

 [[185 181 186]
  [145 141 146]
  [165 161 166]
  ...
  [112 111 121]
  [100  99 109]
  [110 109 119]]

 [[163 159 164]
  [137 133 138]
  [155 151 156]
  

33it [00:07,  5.49it/s, Epoch=1, Loss=2.034462, Mean Loss=2.637113, Mean F-1=0.148808]

???
[[[140 138 144]
  [139 137 143]
  [132 130 136]
  ...
  [161 157 162]
  [164 160 165]
  [165 161 166]]

 [[138 136 142]
  [141 139 145]
  [134 132 138]
  ...
  [156 152 157]
  [158 154 159]
  [159 155 160]]

 [[123 121 127]
  [130 128 134]
  [126 124 130]
  ...
  [155 151 156]
  [156 152 157]
  [156 152 157]]

 ...

 [[129 125 130]
  [102  98 103]
  [106 102 107]
  ...
  [143 137 142]
  [142 136 141]
  [141 135 140]]

 [[105 101 106]
  [ 89  85  90]
  [107 103 108]
  ...
  [143 137 142]
  [142 136 141]
  [142 136 141]]

 [[129 125 130]
  [125 121 126]
  [ 97  93  98]
  ...
  [141 135 140]
  [141 135 140]
  [139 133 138]]]
./data/public/PlantVillage\Tomato_Early_blight\6ccc0cdb-d420-4bc6-9a1a-d195a0521c19___RS_Erly.B 9437.JPG
???
[[[155 151 163]
  [203 199 211]
  [136 132 144]
  ...
  [216 210 215]
  [213 207 212]
  [207 201 206]]

 [[201 197 209]
  [136 132 144]
  [131 127 139]
  ...
  [206 200 205]
  [249 243 248]
  [203 197 202]]

 [[150 146 158]
  [172 168 180]
  [187 183 195]
 

34it [00:07,  5.55it/s, Epoch=1, Loss=1.874955, Mean Loss=2.614696, Mean F-1=0.155542]

???
[[[181 164 168]
  [176 159 163]
  [180 163 167]
  ...
  [114  96 103]
  [129 111 118]
  [138 120 127]]

 [[199 182 186]
  [199 182 186]
  [183 166 170]
  ...
  [196 178 185]
  [134 116 123]
  [124 106 113]]

 [[188 171 175]
  [197 180 184]
  [184 167 171]
  ...
  [120 102 109]
  [160 142 149]
  [116  98 105]]

 ...

 [[167 153 157]
  [177 163 167]
  [168 154 158]
  ...
  [124 110 116]
  [133 119 125]
  [103  89  95]]

 [[167 153 157]
  [174 160 164]
  [163 149 153]
  ...
  [116 102 108]
  [148 134 140]
  [117 103 109]]

 [[164 150 154]
  [170 156 160]
  [160 146 150]
  ...
  [152 138 144]
  [163 149 155]
  [110  96 102]]]
./data/public/PlantVillage\Tomato__Target_Spot\942dbcb4-7c9e-4ec7-beea-cd11383c7d83___Com.G_TgS_FL 0835.JPG
img
torch.Size([16, 3, 224, 224])
???
[[[129 155 142]
  [126 152 139]
  [124 150 136]
  ...
  [197 192 171]
  [197 194 173]
  [198 196 172]]

 [[129 155 142]
  [127 153 140]
  [124 150 136]
  ...
  [192 188 169]
  [193 190 169]
  [191 190 169]]

 [[127 155 1

36it [00:07,  5.51it/s, Epoch=1, Loss=2.411498, Mean Loss=2.594280, Mean F-1=0.165721]

???
[[[175 154 153]
  [168 147 146]
  [163 142 141]
  ...
  [166 149 153]
  [170 153 157]
  [172 155 159]]

 [[171 150 149]
  [168 147 146]
  [165 144 143]
  ...
  [179 162 166]
  [169 152 156]
  [188 171 175]]

 [[180 159 158]
  [178 157 156]
  [177 156 155]
  ...
  [183 166 170]
  [181 164 168]
  [170 153 157]]

 ...

 [[189 175 177]
  [196 182 184]
  [195 181 183]
  ...
  [181 167 171]
  [173 159 163]
  [170 156 160]]

 [[187 173 175]
  [194 180 182]
  [193 179 181]
  ...
  [175 161 165]
  [170 156 160]
  [169 155 159]]

 [[188 174 176]
  [195 181 183]
  [193 179 181]
  ...
  [176 162 166]
  [170 156 160]
  [168 154 158]]]
./data/public/PlantVillage\Tomato_Septoria_leaf_spot\7a7c032c-bc58-43c0-9bf7-26be8baf2660___Matt.S_CG 7605.JPG
???
[[[ 84  65  74]
  [ 98  79  88]
  [ 88  69  78]
  ...
  [ 79  62  75]
  [ 82  65  78]
  [ 94  77  90]]

 [[121 102 111]
  [ 89  70  79]
  [104  85  94]
  ...
  [119 102 115]
  [111  94 107]
  [ 95  78  91]]

 [[139 120 129]
  [106  87  96]
  [161 142 

37it [00:07,  5.54it/s, Epoch=1, Loss=2.505542, Mean Loss=2.591882, Mean F-1=0.166004]

[[[189 190 194]
  [187 188 192]
  [186 187 191]
  ...
  [189 190 194]
  [189 190 194]
  [190 191 195]]

 [[191 192 196]
  [189 190 194]
  [188 189 193]
  ...
  [187 188 192]
  [187 188 192]
  [187 188 192]]

 [[191 192 196]
  [190 191 195]
  [189 190 194]
  ...
  [187 188 192]
  [187 188 192]
  [187 188 192]]

 ...

 [[130 130 144]
  [136 136 150]
  [126 126 140]
  ...
  [113 114 124]
  [138 139 149]
  [121 122 132]]

 [[127 127 141]
  [131 131 145]
  [132 132 146]
  ...
  [132 133 143]
  [140 141 151]
  [120 121 131]]

 [[116 116 130]
  [119 119 133]
  [134 134 148]
  ...
  [153 154 164]
  [138 139 149]
  [134 135 145]]]
./data/public/PlantVillage\Tomato_Early_blight\d53bdcff-1ea7-46c7-9d46-701d104bf130___RS_Erly.B 8353.JPG
???
[[[150 149 159]
  [176 175 185]
  [164 163 173]
  ...
  [169 169 181]
  [148 148 160]
  [135 135 147]]

 [[188 187 197]
  [179 178 188]
  [168 167 177]
  ...
  [168 168 180]
  [122 122 134]
  [135 135 147]]

 [[206 205 215]
  [176 175 185]
  [174 173 183]
  ...

38it [00:08,  5.50it/s, Epoch=1, Loss=1.788742, Mean Loss=2.570746, Mean F-1=0.168997]

???
[[[124 129 130]
  [122 127 128]
  [121 126 127]
  ...
  [138 135 131]
  [138 135 131]
  [138 135 131]]

 [[123 128 129]
  [123 128 129]
  [122 127 128]
  ...
  [138 135 131]
  [138 135 131]
  [138 135 131]]

 [[123 128 129]
  [123 128 129]
  [124 129 130]
  ...
  [137 134 130]
  [137 134 130]
  [137 134 130]]

 ...

 [[ 95 102 105]
  [ 95 102 105]
  [ 99 106 109]
  ...
  [ 68  73  74]
  [ 64  69  70]
  [ 62  67  68]]

 [[ 99 106 109]
  [ 99 106 109]
  [103 110 113]
  ...
  [ 70  75  76]
  [ 68  73  74]
  [ 66  71  72]]

 [[103 110 113]
  [102 109 112]
  [106 113 116]
  ...
  [ 73  78  79]
  [ 72  77  78]
  [ 71  76  77]]]
./data/public/PlantVillage\Tomato__Tomato_YellowLeaf__Curl_Virus\4ffd2596-dce0-42de-90f0-3a383d238975___UF.GRC_YLCV_Lab 02708.JPG
???
[[[125 134 154]
  [126 135 155]
  [121 130 150]
  ...
  [127 134 161]
  [115 122 149]
  [111 118 145]]

 [[120 129 149]
  [121 130 150]
  [117 126 146]
  ...
  [ 95 102 129]
  [100 107 134]
  [114 121 148]]

 [[106 115 135]
  [111 1

39it [00:08,  5.51it/s, Epoch=1, Loss=2.096325, Mean Loss=2.558582, Mean F-1=0.165763]

[[[188 178 190]
  [176 166 178]
  [192 182 194]
  ...
  [201 193 204]
  [211 203 214]
  [216 208 219]]

 [[193 183 195]
  [170 160 172]
  [172 162 174]
  ...
  [188 180 191]
  [178 170 181]
  [201 193 204]]

 [[172 162 174]
  [158 148 160]
  [213 203 215]
  ...
  [207 199 210]
  [194 186 197]
  [192 184 195]]

 ...

 [[138 133 148]
  [167 162 177]
  [162 157 172]
  ...
  [189 184 199]
  [165 160 175]
  [154 149 164]]

 [[173 168 183]
  [180 175 190]
  [166 161 176]
  ...
  [159 154 169]
  [120 115 130]
  [188 183 198]]

 [[142 137 152]
  [185 180 195]
  [191 186 201]
  ...
  [239 234 249]
  [205 200 215]
  [179 174 189]]]
./data/public/PlantVillage\Tomato_Septoria_leaf_spot\f3d54943-501d-41ee-a07d-541dd03ff14c___Matt.S_CG 6802.JPG
???
[[[128 131 136]
  [140 143 148]
  [128 131 136]
  ...
  [157 157 163]
  [145 145 151]
  [155 155 161]]

 [[116 119 124]
  [136 139 144]
  [132 135 140]
  ...
  [152 152 158]
  [142 142 148]
  [145 145 151]]

 [[123 126 131]
  [134 137 142]
  [131 134 139]

40it [00:08,  5.53it/s, Epoch=1, Loss=2.309328, Mean Loss=2.552350, Mean F-1=0.161619]

???
[[[107 106 116]
  [119 118 128]
  [117 116 126]
  ...
  [144 144 150]
  [144 144 150]
  [142 142 148]]

 [[ 87  86  96]
  [102 101 111]
  [106 105 115]
  ...
  [134 134 140]
  [132 132 138]
  [130 130 136]]

 [[ 94  93 103]
  [105 104 114]
  [104 103 113]
  ...
  [132 132 138]
  [132 132 138]
  [132 132 138]]

 ...

 [[120 118 124]
  [124 122 128]
  [120 118 124]
  ...
  [142 141 145]
  [143 142 146]
  [144 143 147]]

 [[127 125 131]
  [129 127 133]
  [125 123 129]
  ...
  [138 137 141]
  [139 138 142]
  [140 139 143]]

 [[123 121 127]
  [123 121 127]
  [119 117 123]
  ...
  [145 144 148]
  [147 146 150]
  [148 147 151]]]
./data/public/PlantVillage\Tomato_Bacterial_spot\c41baf9d-cf9e-4acb-a7a8-bb0c7e201621___GCREC_Bact.Sp 3492.JPG
???
[[[124 118 123]
  [127 121 126]
  [130 124 129]
  ...
  [121 120 122]
  [108 107 109]
  [106 105 107]]

 [[125 119 124]
  [127 121 126]
  [129 123 128]
  ...
  [112 111 113]
  [110 109 111]
  [113 112 114]]

 [[126 120 125]
  [126 120 125]
  [127 121 

41it [00:08,  5.46it/s, Epoch=1, Loss=2.630571, Mean Loss=2.554258, Mean F-1=0.164723]

[[[150 151 161]
  [163 164 174]
  [145 146 156]
  ...
  [135 131 142]
  [148 144 155]
  [161 157 168]]

 [[168 169 179]
  [178 179 189]
  [163 164 174]
  ...
  [145 141 152]
  [128 124 135]
  [142 138 149]]

 [[161 162 172]
  [148 149 159]
  [159 160 170]
  ...
  [151 147 158]
  [165 161 172]
  [148 144 155]]

 ...

 [[ 98  98 114]
  [ 99  99 115]
  [ 95  95 111]
  ...
  [104 104 118]
  [ 98  98 112]
  [ 94  94 108]]

 [[105 105 121]
  [109 109 125]
  [112 112 128]
  ...
  [109 109 123]
  [ 93  93 107]
  [ 85  85  99]]

 [[ 94  94 110]
  [100 100 116]
  [109 109 125]
  ...
  [ 87  87 101]
  [113 113 127]
  [ 89  89 103]]]
./data/public/PlantVillage\Tomato_Spider_mites_Two_spotted_spider_mite\e13060fe-90fb-49c9-ab46-9a4cfd68c02a___Com.G_SpM_FL 1749.JPG
???
[[[ 97 106 126]
  [ 87  96 116]
  [ 96 105 125]
  ...
  [154 162 179]
  [159 167 184]
  [151 159 176]]

 [[123 132 152]
  [107 116 136]
  [ 96 105 125]
  ...
  [162 170 187]
  [164 172 189]
  [160 168 185]]

 [[145 154 174]
  [105 114

42it [00:08,  5.61it/s, Epoch=1, Loss=1.882595, Mean Loss=2.538266, Mean F-1=0.164293]

???
[[[125 107 108]
  [122 104 105]
  [123 105 106]
  ...
  [133 113 112]
  [133 113 112]
  [134 114 113]]

 [[133 115 116]
  [127 109 110]
  [124 106 107]
  ...
  [126 106 105]
  [125 105 104]
  [126 106 105]]

 [[133 115 116]
  [126 108 109]
  [124 106 107]
  ...
  [126 106 105]
  [125 105 104]
  [126 106 105]]

 ...

 [[159 140 135]
  [159 140 135]
  [156 137 132]
  ...
  [165 145 140]
  [164 144 139]
  [155 135 130]]

 [[161 142 137]
  [161 142 137]
  [156 137 132]
  ...
  [161 141 136]
  [164 144 139]
  [162 142 137]]

 [[158 139 134]
  [158 139 134]
  [154 135 130]
  ...
  [164 144 139]
  [169 149 144]
  [175 155 150]]]
./data/public/PlantVillage\Tomato_Leaf_Mold\bb98de22-463a-4ad2-8ad1-e65d1ea463c8___Crnl_L.Mold 7160.JPG
???
[[[159 152 167]
  [138 131 146]
  [185 178 193]
  ...
  [202 194 205]
  [172 164 175]
  [185 177 188]]

 [[164 157 172]
  [187 180 195]
  [160 153 168]
  ...
  [206 198 209]
  [194 186 197]
  [217 209 220]]

 [[176 169 184]
  [163 156 171]
  [191 184 199]
  

43it [00:09,  5.41it/s, Epoch=1, Loss=2.420877, Mean Loss=2.535536, Mean F-1=0.165481]

???
[[[103  79  89]
  [103  79  89]
  [112  88  98]
  ...
  [143 117 123]
  [143 117 123]
  [143 117 123]]

 [[179 155 165]
  [123  99 109]
  [ 94  70  80]
  ...
  [143 117 123]
  [143 117 123]
  [143 117 123]]

 [[ 85  61  71]
  [134 110 120]
  [ 92  68  78]
  ...
  [142 116 122]
  [144 118 124]
  [145 119 125]]

 ...

 [[121  94 103]
  [123  96 105]
  [125  98 107]
  ...
  [  8  54  25]
  [  7  55  26]
  [  8  56  27]]

 [[118  91 100]
  [119  92 101]
  [121  94 103]
  ...
  [  3  52  20]
  [  3  52  20]
  [  3  52  20]]

 [[118  91 100]
  [119  92 101]
  [120  93 102]
  ...
  [  0  48  16]
  [  0  47  15]
  [  0  46  14]]]
./data/public/PlantVillage\Pepper__bell___Bacterial_spot\57ff0455-861f-4f25-9598-c2954ca44027___JR_B.Spot 3115.JPG
???
[[[184 176 183]
  [187 179 186]
  [180 172 179]
  ...
  [105  93  99]
  [114 102 108]
  [123 111 117]]

 [[161 153 160]
  [160 152 159]
  [161 153 160]
  ...
  [136 124 130]
  [142 130 136]
  [148 136 142]]

 [[143 135 142]
  [154 146 153]
  [150 

44it [00:09,  5.26it/s, Epoch=1, Loss=1.924851, Mean Loss=2.521657, Mean F-1=0.170378]

???
[[[176 177 168]
  [175 176 167]
  [173 174 165]
  ...
  [135 140 139]
  [136 141 140]
  [136 141 140]]

 [[176 177 168]
  [175 176 167]
  [174 175 166]
  ...
  [135 140 139]
  [135 140 139]
  [136 141 140]]

 [[176 177 168]
  [175 176 167]
  [174 175 166]
  ...
  [134 139 138]
  [135 140 139]
  [135 140 139]]

 ...

 [[193 195 183]
  [192 194 182]
  [190 192 180]
  ...
  [ 90 102 106]
  [ 91 103 107]
  [ 91 103 107]]

 [[194 196 184]
  [193 195 183]
  [191 193 181]
  ...
  [ 91 103 107]
  [ 91 103 107]
  [ 92 104 108]]

 [[194 196 184]
  [194 196 184]
  [192 194 182]
  ...
  [ 91 103 107]
  [ 92 104 108]
  [ 92 104 108]]]
./data/public/PlantDoc/train/P1020430_jpg.rf.ac6773471599d3cd9a6c8b3c083fc77c.jpg
???
[[[ 79  72  87]
  [126 119 134]
  [135 128 143]
  ...
  [217 213 219]
  [213 209 215]
  [206 202 208]]

 [[111 104 119]
  [107 100 115]
  [140 133 148]
  ...
  [225 221 227]
  [220 216 222]
  [211 207 213]]

 [[109 102 117]
  [118 111 126]
  [158 151 166]
  ...
  [225 221 227]
  

45it [00:09,  5.34it/s, Epoch=1, Loss=1.762910, Mean Loss=2.504796, Mean F-1=0.169173]

???
[[[150 149 159]
  [147 146 156]
  [146 145 155]
  ...
  [142 140 152]
  [141 139 151]
  [137 135 147]]

 [[155 154 164]
  [150 149 159]
  [147 146 156]
  ...
  [138 136 148]
  [137 135 147]
  [135 133 145]]

 [[160 159 169]
  [155 154 164]
  [150 149 159]
  ...
  [140 138 150]
  [139 137 149]
  [137 135 147]]

 ...

 [[110 110 124]
  [117 117 131]
  [123 123 137]
  ...
  [122 121 137]
  [122 121 137]
  [119 118 134]]

 [[114 114 128]
  [115 115 129]
  [115 115 129]
  ...
  [121 120 136]
  [119 118 134]
  [119 118 134]]

 [[114 114 128]
  [109 109 123]
  [105 105 119]
  ...
  [122 121 137]
  [118 117 133]
  [120 119 135]]]
./data/public/PlantVillage\Tomato_Early_blight\f88be630-f853-48f8-b546-a2f7966368a2___RS_Erly.B 7418.JPG
???
[[[119 120 118]
  [119 120 118]
  [119 120 118]
  ...
  [114 112 111]
  [114 112 111]
  [114 112 111]]

 [[121 122 120]
  [120 121 119]
  [119 120 118]
  ...
  [115 113 112]
  [115 113 112]
  [115 113 112]]

 [[124 125 123]
  [122 123 121]
  [119 120 118]
 

46it [00:09,  5.31it/s, Epoch=1, Loss=1.812490, Mean Loss=2.489746, Mean F-1=0.173880]

???
[[[133 122 138]
  [113 102 118]
  [116 105 121]
  ...
  [128 117 133]
  [136 125 141]
  [139 128 144]]

 [[112 101 117]
  [119 108 124]
  [143 132 148]
  ...
  [122 111 127]
  [129 118 134]
  [131 120 136]]

 [[126 115 131]
  [126 115 131]
  [151 140 156]
  ...
  [129 118 134]
  [137 126 142]
  [130 119 135]]

 ...

 [[178 164 176]
  [162 148 160]
  [179 165 177]
  ...
  [164 150 162]
  [139 125 137]
  [171 157 169]]

 [[192 178 190]
  [162 148 160]
  [168 154 166]
  ...
  [162 148 160]
  [164 150 162]
  [177 163 175]]

 [[187 173 185]
  [173 159 171]
  [188 174 186]
  ...
  [170 156 168]
  [178 164 176]
  [159 145 157]]]
./data/public/PlantVillage\Tomato__Tomato_mosaic_virus\46b3cb66-9265-464f-9b0a-ac23eb72a4a0___PSU_CG 2411.JPG
???
[[[130 126 131]
  [134 130 135]
  [128 124 129]
  ...
  [182 176 181]
  [137 131 136]
  [128 122 127]]

 [[111 107 112]
  [159 155 160]
  [137 133 138]
  ...
  [133 127 132]
  [110 104 109]
  [171 165 170]]

 [[117 113 118]
  [140 136 141]
  [136 132 1

47it [00:09,  5.29it/s, Epoch=1, Loss=2.019280, Mean Loss=2.479736, Mean F-1=0.177824]

[[[169 165 177]
  [167 163 175]
  [167 163 175]
  ...
  [146 141 156]
  [139 134 149]
  [150 145 160]]

 [[166 162 174]
  [170 166 178]
  [175 171 183]
  ...
  [156 151 166]
  [150 145 160]
  [103  98 113]]

 [[149 145 157]
  [156 152 164]
  [165 161 173]
  ...
  [154 149 164]
  [161 156 171]
  [147 142 157]]

 ...

 [[193 189 200]
  [191 187 198]
  [171 167 178]
  ...
  [134 131 146]
  [121 118 133]
  [133 130 145]]

 [[191 187 198]
  [168 164 175]
  [167 163 174]
  ...
  [142 139 154]
  [143 140 155]
  [131 128 143]]

 [[154 150 161]
  [195 191 202]
  [193 189 200]
  ...
  [132 129 144]
  [149 146 161]
  [132 129 144]]]
./data/public/PlantVillage\Tomato__Target_Spot\e6efb6e3-7e58-441d-808f-bdb535f8ad70___Com.G_TgS_FL 9764.JPG
???
[[[158 148 160]
  [182 172 184]
  [194 184 196]
  ...
  [176 169 182]
  [227 220 233]
  [151 144 157]]

 [[186 176 188]
  [183 173 185]
  [180 170 182]
  ...
  [221 214 227]
  [176 169 182]
  [168 161 174]]

 [[175 165 177]
  [165 155 167]
  [165 155 167]
  

48it [00:10,  5.23it/s, Epoch=1, Loss=1.917496, Mean Loss=2.468022, Mean F-1=0.186967]

???
[[[139 139 151]
  [138 138 150]
  [142 142 154]
  ...
  [150 151 161]
  [141 142 152]
  [142 143 153]]

 [[151 151 163]
  [147 147 159]
  [146 146 158]
  ...
  [147 148 158]
  [142 143 153]
  [147 148 158]]

 [[147 147 159]
  [141 141 153]
  [139 139 151]
  ...
  [142 143 153]
  [141 142 152]
  [150 151 161]]

 ...

 [[ 98  99 113]
  [ 95  96 110]
  [ 96  97 111]
  ...
  [101 102 116]
  [ 98  99 113]
  [100 101 115]]

 [[ 90  91 105]
  [ 94  95 109]
  [101 102 116]
  ...
  [101 102 116]
  [100 101 115]
  [102 103 117]]

 [[104 105 119]
  [ 90  91 105]
  [ 81  82  96]
  ...
  [100 101 115]
  [101 102 116]
  [106 107 121]]]
./data/public/PlantVillage\Tomato_Bacterial_spot\3ce6b91a-b40d-4703-95ba-175ea70ddc27___GCREC_Bact.Sp 5667.JPG
???
[[[102  98 104]
  [105 101 107]
  [110 106 112]
  ...
  [125 121 127]
  [123 119 125]
  [114 110 116]]

 [[105 101 107]
  [103  99 105]
  [103  99 105]
  ...
  [120 116 122]
  [119 115 121]
  [114 110 116]]

 [[109 105 111]
  [103  99 105]
  [100  96 

49it [00:10,  5.31it/s, Epoch=1, Loss=2.124720, Mean Loss=2.461016, Mean F-1=0.193550]

???
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
./data/public/PlantDoc/train/Early_Blight_of_Tomato177_jpg.rf.63629c4d05a55a5f8cd0f4133d81d44f.jpg
???
[[[239  93 141]
  [236  94 141]
  [230  94 142]
  ...
  [243 113 160]
  [249 113 161]
  [254 114 161]]

 [[220  74 122]
  [235  93 140]
  [233  98 146]
  ...
  [244 116 165]
  [252 116 164]
  [255 116 163]]

 [[210  66 115]
  [227  86 135]
  [230  98 145]
  ...
  [246 118 167]
  [251 115 163]
  [252 114 162]]

 ...

 [[231  81 141]
  [224  97 153]
  [198 117 166]
  ...
  [249 182 209]
  [240 184 213]
  [235 186 214]]

 [[217  86 143]
  [216  96 151]
  [212 108 161]
  ...
  [

50it [00:10,  5.48it/s, Epoch=1, Loss=1.950105, Mean Loss=2.450798, Mean F-1=0.193847]

???
[[[184 112 188]
  [185 116 191]
  [189 120 195]
  ...
  [146 116 165]
  [151 121 170]
  [163 133 182]]

 [[186 114 190]
  [188 119 194]
  [192 123 198]
  ...
  [146 117 163]
  [150 120 169]
  [160 131 177]]

 [[186 114 190]
  [189 120 195]
  [194 125 200]
  ...
  [149 118 163]
  [152 120 167]
  [158 127 172]]

 ...

 [[174 152 117]
  [172 153 116]
  [149 132  93]
  ...
  [196 161 228]
  [192 157 224]
  [186 151 218]]

 [[182 160 132]
  [174 153 122]
  [146 127  92]
  ...
  [199 164 231]
  [197 163 228]
  [191 157 222]]

 [[186 162 138]
  [175 152 126]
  [144 125  92]
  ...
  [202 167 234]
  [201 167 232]
  [197 163 228]]]
./data/public/PlantDoc/train/1b_jpg.rf.ab0c246abee404d74b074808f01955ac.jpg
???
[[[135 118 121]
  [137 120 123]
  [133 116 119]
  ...
  [100  82  89]
  [126 108 115]
  [141 123 130]]

 [[190 173 176]
  [233 216 219]
  [191 174 177]
  ...
  [159 141 148]
  [129 111 118]
  [121 103 110]]

 [[175 158 161]
  [160 143 146]
  [230 213 216]
  ...
  [152 134 141]
  [ 90  

50it [00:10,  4.79it/s, Epoch=1, Loss=1.950105, Mean Loss=2.450798, Mean F-1=0.193847]


???
[[[202 204 214]
  [202 204 214]
  [203 205 215]
  ...
  [166 168 179]
  [173 175 186]
  [168 170 181]]

 [[196 198 208]
  [192 194 204]
  [188 190 200]
  ...
  [175 177 188]
  [175 177 188]
  [164 166 177]]

 [[185 187 197]
  [181 183 193]
  [179 181 191]
  ...
  [172 174 185]
  [169 171 182]
  [155 157 168]]

 ...

 [[103 108 129]
  [ 94  99 120]
  [ 88  93 114]
  ...
  [103 103 121]
  [106 106 124]
  [115 115 133]]

 [[119 124 145]
  [112 117 138]
  [105 110 131]
  ...
  [ 98  98 116]
  [100 100 118]
  [106 106 124]]

 [[109 114 135]
  [106 111 132]
  [103 108 129]
  ...
  [101 101 119]
  [102 102 120]
  [105 105 123]]]
./data/public/PlantVillage\Tomato_Spider_mites_Two_spotted_spider_mite\fff8949b-3721-4f42-a489-8d39753fe7bb___Com.G_SpM_FL 8656.JPG
???
[[[148 147 157]
  [146 145 155]
  [165 164 174]
  ...
  [150 150 164]
  [142 142 156]
  [137 137 151]]

 [[157 156 166]
  [160 159 169]
  [160 159 169]
  ...
  [152 152 166]
  [154 154 168]
  [137 137 151]]

 [[170 169 179]
  [177

error: OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-uzca7qz1\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'


In [50]:
img = cv2.imread('./data/public/PlantDoc/train/leaves-isolated-on-white-background-picture-id537925565_k=6&m=537925565&s=612x612&w=0&h=Ogzc4YHTI4i4q9aiTIG6Zq2sAMv6xTKiDlCmYANlzK8=_jpg.rf.dab246267da7f3a21649231a184bc0c5.jpg')
img.shape

AttributeError: 'NoneType' object has no attribute 'shape'

In [ ]:
a = 'IMG_6029-001_1500x1500%253E_JPG?1403119544_jpg.rf.01aae68643601f970bad558834c627ae.jpg'

if '?' in a :
    print("asdf")

In [55]:
import timm

class DeiT_(nn.Module):
    def __init__(self, model_name, n_classes):
        super(DeiT_, self).__init__()
        self.model = timm.create_model(model_name, num_classes=n_classes, pretrained=False)
    
    def forward(self, inputs):
        output = self.model(inputs)
        return output

model = DeiT_(model_name, 15)
model.load_state_dict(torch.load('./model/public_vill_pretrain_Deit_S16patch224.pt', map_location=device))
model.to(device).eval()


DeiT_(
  (model): VisionTransformer(
    (patch_embed): PatchEmbed(
      (proj): Conv2d(3, 384, kernel_size=(16, 16), stride=(16, 16))
      (norm): Identity()
    )
    (pos_drop): Dropout(p=0.0, inplace=False)
    (blocks): Sequential(
      (0): Block(
        (norm1): LayerNorm((384,), eps=1e-06, elementwise_affine=True)
        (attn): Attention(
          (qkv): Linear(in_features=384, out_features=1152, bias=True)
          (attn_drop): Dropout(p=0.0, inplace=False)
          (proj): Linear(in_features=384, out_features=384, bias=True)
          (proj_drop): Dropout(p=0.0, inplace=False)
        )
        (drop_path): Identity()
        (norm2): LayerNorm((384,), eps=1e-06, elementwise_affine=True)
        (mlp): Mlp(
          (fc1): Linear(in_features=384, out_features=1536, bias=True)
          (act): GELU()
          (fc2): Linear(in_features=1536, out_features=384, bias=True)
          (drop): Dropout(p=0.0, inplace=False)
        )
      )
      (1): Block(
        (norm1

In [61]:
data_ = torch.rand(1,3,224,224).to(device)

pred = model(data_)
pred.shape

torch.Size([1, 15])